/*jslint */
/*global AdobeEdge: false, window: false, document: false, console:false, alert: false */
(function (compId) {

    "use strict";
    var im='images/',
        aud='media/',
        vid='media/',
        js='js/',
        fonts = {
        },
        opts = {
            'gAudioPreloadPreference': 'auto',
            'gVideoPreloadPreference': 'auto'
        },
        resources = [
        ],
        scripts = [
        ],
        symbols = {
            "stage": {
                version: "6.0.0",
                minimumCompatibleVersion: "5.0.0",
                build: "6.0.0.400",
                scaleToFit: "none",
                centerStage: "none",
                resizeInstances: false,
                content: {
                    dom: [
                        {
                            id: 'back',
                            display: 'block',
                            type: 'image',
                            rect: ['193px', '126px', '160px', '61px', 'auto', 'auto'],
                            opacity: '1',
                            fill: ["rgba(0,0,0,0)",im+"back.svg",'0px','0px']
                        },
                        {
                            id: 'towe',
                            display: 'block',
                            type: 'image',
                            rect: ['204px', '19px', '68px', '41px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"towe.svg",'0px','0px']
                        },
                        {
                            id: 'Text7',
                            display: 'none',
                            type: 'text',
                            rect: ['420px', '277px', 'auto', 'auto', 'auto', 'auto'],
                            opacity: '0',
                            text: "<p style=\"margin: 0px;\">​6x-8x</p>",
                            align: "left",
                            font: ['Arial, Helvetica, sans-serif', [29, "px"], "rgba(0,0,0,1)", "400", "none", "normal", "break-word", "nowrap"],
                            textStyle: ["", "", "", "", "none"]
                        },
                        {
                            id: 'covre',
                            display: 'block',
                            type: 'image',
                            rect: ['203px', '12px', '99px', '66px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"covre.svg",'0px','0px']
                        },
                        {
                            id: 'heatpak',
                            display: 'block',
                            type: 'image',
                            rect: ['409px', '78px', '55px', '74px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"heatpak.svg",'0px','0px']
                        },
                        {
                            id: 'media12',
                            display: 'none',
                            type: 'audio',
                            tag: 'audio',
                            rect: ['0', '0', '320px', '45px', 'auto', 'auto'],
                            source: [aud+"media12.wav"],
                            preload: 'auto'
                        },
                        {
                            id: 'thermo2',
                            display: 'none',
                            type: 'image',
                            rect: ['421px', '174px', '45px', '163px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"thermo.svg",'0px','0px']
                        },
                        {
                            id: 'lid',
                            display: 'block',
                            type: 'image',
                            rect: ['192px', '117px', '161px', '57px', 'auto', 'auto'],
                            opacity: '1',
                            fill: ["rgba(0,0,0,0)",im+"lid.svg",'0px','0px']
                        },
                        {
                            id: 'hydro',
                            display: 'block',
                            type: 'image',
                            rect: ['191px', '143px', '168px', '236px', 'auto', 'auto'],
                            opacity: '1',
                            fill: ["rgba(0,0,0,0)",im+"hydro.svg",'0px','0px']
                        },
                        {
                            id: 'Text2',
                            type: 'text',
                            rect: ['403px', '96px', '105px', '50px', 'auto', 'auto'],
                            opacity: '0',
                            text: "<p style=\"margin: 0px;\">​158°F&nbsp;</p>",
                            align: "left",
                            font: ['Arial, Helvetica, sans-serif', [29, "px"], "rgba(0,0,0,1)", "400", "none", "normal", "break-word", "normal"],
                            textStyle: ["", "", "", "", "none"]
                        },
                        {
                            id: 'Text3',
                            type: 'text',
                            rect: ['399px', '131px', 'auto', 'auto', 'auto', 'auto'],
                            opacity: '0',
                            text: "<p style=\"margin: 0px;\">​167° F</p>",
                            align: "left",
                            font: ['Arial, Helvetica, sans-serif', [29, "px"], "rgba(0,0,0,1)", "400", "none", "normal", "break-word", "nowrap"],
                            textStyle: ["", "", "", "", "none"]
                        },
                        {
                            id: 'hp1',
                            type: 'image',
                            rect: ['417px', '285px', '92px', '73px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"hp1.svg",'0px','0px']
                        },
                        {
                            id: 'hp2',
                            type: 'image',
                            rect: ['47px', '24px', '70px', '55px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"hp2.svg",'0px','0px']
                        },
                        {
                            id: 'hp3',
                            type: 'image',
                            rect: ['47px', '309px', '65px', '37px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"hp3.svg",'0px','0px']
                        },
                        {
                            id: 'hp4',
                            type: 'image',
                            rect: ['36px', '173px', '36px', '37px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"hp4.svg",'0px','0px']
                        },
                        {
                            id: 'hp5',
                            type: 'image',
                            rect: ['403px', '179px', '115px', '29px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"hp5.svg",'0px','0px']
                        },
                        {
                            id: 'Text',
                            display: 'none',
                            type: 'text',
                            rect: ['189px', '36px', 'auto', 'auto', 'auto', 'auto'],
                            opacity: '0',
                            text: "<p style=\"margin: 0px;\">​<span style=\"font-weight: 500;\">Hydrocollator</span></p>",
                            font: ['Arial, Helvetica, sans-serif', [29, "px"], "rgba(0,0,0,1)", "normal", "none", "", "break-word", "nowrap"]
                        },
                        {
                            id: 'Text5',
                            type: 'text',
                            rect: ['207px', '36px', 'auto', 'auto', 'auto', 'auto'],
                            opacity: '0',
                            text: "<p style=\"margin: 0px;\">​<span style=\"font-family: Verdana, Geneva, sans-serif;\">2 HOURS</span></p>",
                            align: "left",
                            font: ['Arial, Helvetica, sans-serif', [29, "px"], "rgba(0,0,0,1)", "400", "none", "normal", "break-word", "nowrap"],
                            textStyle: ["", "", "", "", "none"]
                        },
                        {
                            id: 'Text6',
                            type: 'text',
                            rect: ['183px', '39px', 'auto', 'auto', 'auto', 'auto'],
                            opacity: '0',
                            text: "<p style=\"margin: 0px;\">​30 MINUTES</p>",
                            align: "left",
                            font: ['Arial, Helvetica, sans-serif', [29, "px"], "rgba(0,0,0,1)", "400", "none", "normal", "break-word", "nowrap"],
                            textStyle: ["", "", "", "", "none"]
                        },
                        {
                            id: 'all',
                            display: 'none',
                            type: 'image',
                            rect: ['17px', '105px', '515px', '195px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"all.svg",'0px','0px']
                        },
                        {
                            id: 'Text4',
                            type: 'text',
                            rect: ['157px', '58px', 'auto', 'auto', 'auto', 'auto'],
                            opacity: '0',
                            text: "<p style=\"margin: 0px;\">​Hotpacks</p>",
                            font: ['Arial, Helvetica, sans-serif', [24, ""], "rgba(0,0,0,1)", "normal", "none", "", "break-word", "nowrap"]
                        },
                        {
                            id: 'Text8',
                            type: 'text',
                            rect: ['58px', '302px', 'auto', 'auto', 'auto', 'auto'],
                            opacity: '0',
                            text: "<p style=\"margin: 0px;\">​Towel</p>",
                            align: "left",
                            font: ['Arial, Helvetica, sans-serif', [24, "px"], "rgba(0,0,0,1)", "400", "none", "normal", "break-word", "nowrap"],
                            textStyle: ["", "", "", "", "none"]
                        },
                        {
                            id: 'Text9',
                            type: 'text',
                            rect: ['229px', '309px', 'auto', 'auto', 'auto', 'auto'],
                            opacity: '0',
                            text: "<p style=\"margin: 0px;\">​Covers</p>",
                            align: "left",
                            font: ['Arial, Helvetica, sans-serif', [24, "px"], "rgba(0,0,0,1)", "400", "none", "normal", "break-word", "nowrap"],
                            textStyle: ["", "", "", "", "none"]
                        },
                        {
                            id: 'Text10',
                            type: 'text',
                            rect: ['387px', '61px', 'auto', 'auto', 'auto', 'auto'],
                            opacity: '0',
                            text: "<p style=\"margin: 0px;\">​Hydrocollator</p>",
                            align: "left",
                            font: ['Arial, Helvetica, sans-serif', [24, "px"], "rgba(0,0,0,1)", "400", "none", "normal", "break-word", "nowrap"],
                            textStyle: ["", "", "", "", "none"]
                        }
                    ],
                    style: {
                        '${Stage}': {
                            isStage: true,
                            rect: ['null', 'null', '550px', '400px', 'auto', 'auto'],
                            overflow: 'hidden',
                            fill: ["rgba(255,255,255,1)"]
                        }
                    }
                },
                timeline: {
                    duration: 56942.177,
                    autoPlay: true,
                    data: [
                        [
                            "eid276",
                            "width",
                            30000,
                            921,
                            "linear",
                            "${hp2}",
                            '70px',
                            '92px'
                        ],
                        [
                            "eid4",
                            "display",
                            0,
                            0,
                            "linear",
                            "${towe}",
                            'block',
                            'block'
                        ],
                        [
                            "eid309",
                            "left",
                            27000,
                            498,
                            "linear",
                            "${covre}",
                            '609px',
                            '203px'
                        ],
                        [
                            "eid199",
                            "left",
                            16254,
                            1082,
                            "linear",
                            "${thermo2}",
                            '421px',
                            '426px'
                        ],
                        [
                            "eid203",
                            "left",
                            17336,
                            943,
                            "linear",
                            "${thermo2}",
                            '426px',
                            '265px'
                        ],
                        [
                            "eid72",
                            "left",
                            0,
                            0,
                            "linear",
                            "${hydro}",
                            '191px',
                            '191px'
                        ],
                        [
                            "eid291",
                            "height",
                            32432,
                            600,
                            "linear",
                            "${hp5}",
                            '29px',
                            '41px'
                        ],
                        [
                            "eid107",
                            "left",
                            0,
                            0,
                            "linear",
                            "${back}",
                            '193px',
                            '193px'
                        ],
                        [
                            "eid2",
                            "display",
                            0,
                            0,
                            "linear",
                            "${covre}",
                            'block',
                            'block'
                        ],
                        [
                            "eid61",
                            "width",
                            0,
                            0,
                            "linear",
                            "${hydro}",
                            '168px',
                            '168px'
                        ],
                        [
                            "eid193",
                            "opacity",
                            12023,
                            478,
                            "linear",
                            "${Text2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid197",
                            "opacity",
                            15499,
                            755,
                            "linear",
                            "${Text2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid125",
                            "top",
                            0,
                            0,
                            "linear",
                            "${heatpak}",
                            '36px',
                            '36px'
                        ],
                        [
                            "eid219",
                            "top",
                            20468,
                            532,
                            "linear",
                            "${heatpak}",
                            '36px',
                            '94px'
                        ],
                        [
                            "eid255",
                            "top",
                            21000,
                            3156,
                            "linear",
                            "${heatpak}",
                            '94px',
                            '131px'
                        ],
                        [
                            "eid278",
                            "top",
                            30921,
                            792,
                            "linear",
                            "${heatpak}",
                            '131px',
                            '19px'
                        ],
                        [
                            "eid345",
                            "top",
                            38545,
                            853,
                            "linear",
                            "${heatpak}",
                            '19px',
                            '68px'
                        ],
                        [
                            "eid351",
                            "top",
                            41000,
                            489,
                            "linear",
                            "${heatpak}",
                            '68px',
                            '78px'
                        ],
                        [
                            "eid73",
                            "top",
                            0,
                            0,
                            "linear",
                            "${hydro}",
                            '143px',
                            '143px'
                        ],
                        [
                            "eid366",
                            "left",
                            41489,
                            0,
                            "linear",
                            "${all}",
                            '17px',
                            '17px'
                        ],
                        [
                            "eid381",
                            "opacity",
                            51864,
                            1136,
                            "linear",
                            "${Text9}",
                            '0',
                            '1'
                        ],
                        [
                            "eid267",
                            "opacity",
                            22491,
                            983,
                            "linear",
                            "${Text5}",
                            '0',
                            '1'
                        ],
                        [
                            "eid268",
                            "opacity",
                            25000,
                            1118,
                            "linear",
                            "${Text5}",
                            '1',
                            '0'
                        ],
                        [
                            "eid166",
                            "left",
                            10774,
                            762,
                            "linear",
                            "${hp4}",
                            '433px',
                            '777px'
                        ],
                        [
                            "eid212",
                            "left",
                            11536,
                            9464,
                            "linear",
                            "${hp4}",
                            '777px',
                            '60px'
                        ],
                        [
                            "eid252",
                            "left",
                            21000,
                            3156,
                            "linear",
                            "${hp4}",
                            '60px',
                            '56px'
                        ],
                        [
                            "eid286",
                            "left",
                            31713,
                            719,
                            "linear",
                            "${hp4}",
                            '56px',
                            '36px'
                        ],
                        [
                            "eid296",
                            "width",
                            33032,
                            633,
                            "linear",
                            "${hp3}",
                            '65px',
                            '86px'
                        ],
                        [
                            "eid338",
                            "display",
                            43567,
                            0,
                            "linear",
                            "${Text7}",
                            'none',
                            'block'
                        ],
                        [
                            "eid7",
                            "display",
                            0,
                            0,
                            "linear",
                            "${back}",
                            'block',
                            'block'
                        ],
                        [
                            "eid129",
                            "opacity",
                            0,
                            1000,
                            "linear",
                            "${heatpak}",
                            '0',
                            '1'
                        ],
                        [
                            "eid143",
                            "opacity",
                            8511,
                            515,
                            "linear",
                            "${heatpak}",
                            '1',
                            '0'
                        ],
                        [
                            "eid229",
                            "opacity",
                            13471,
                            0,
                            "linear",
                            "${heatpak}",
                            '0',
                            '0'
                        ],
                        [
                            "eid236",
                            "opacity",
                            20468,
                            0,
                            "linear",
                            "${heatpak}",
                            '0',
                            '0'
                        ],
                        [
                            "eid247",
                            "opacity",
                            21000,
                            1491,
                            "linear",
                            "${heatpak}",
                            '0',
                            '1'
                        ],
                        [
                            "eid305",
                            "opacity",
                            37000,
                            997,
                            "linear",
                            "${heatpak}",
                            '1',
                            '0'
                        ],
                        [
                            "eid354",
                            "opacity",
                            45000,
                            1458,
                            "linear",
                            "${heatpak}",
                            '0',
                            '1'
                        ],
                        [
                            "eid358",
                            "opacity",
                            50000,
                            853,
                            "linear",
                            "${heatpak}",
                            '1',
                            '0'
                        ],
                        [
                            "eid195",
                            "opacity",
                            13471,
                            529,
                            "linear",
                            "${Text3}",
                            '0',
                            '1'
                        ],
                        [
                            "eid196",
                            "opacity",
                            15499,
                            755,
                            "linear",
                            "${Text3}",
                            '1',
                            '0'
                        ],
                        [
                            "eid153",
                            "display",
                            10774,
                            0,
                            "linear",
                            "${thermo2}",
                            'none',
                            'block'
                        ],
                        [
                            "eid133",
                            "opacity",
                            1693,
                            1307,
                            "linear",
                            "${hp1}",
                            '0',
                            '1'
                        ],
                        [
                            "eid147",
                            "opacity",
                            8511,
                            515,
                            "linear",
                            "${hp1}",
                            '1',
                            '0'
                        ],
                        [
                            "eid230",
                            "opacity",
                            13000,
                            0,
                            "linear",
                            "${hp1}",
                            '0',
                            '0'
                        ],
                        [
                            "eid238",
                            "opacity",
                            13471,
                            0,
                            "linear",
                            "${hp1}",
                            '0',
                            '0'
                        ],
                        [
                            "eid248",
                            "opacity",
                            21000,
                            1491,
                            "linear",
                            "${hp1}",
                            '0',
                            '1'
                        ],
                        [
                            "eid303",
                            "opacity",
                            37000,
                            997,
                            "linear",
                            "${hp1}",
                            '1',
                            '0'
                        ],
                        [
                            "eid169",
                            "top",
                            10774,
                            762,
                            "linear",
                            "${hp2}",
                            '104px',
                            '-19px'
                        ],
                        [
                            "eid215",
                            "top",
                            11536,
                            9464,
                            "linear",
                            "${hp2}",
                            '-19px',
                            '119px'
                        ],
                        [
                            "eid261",
                            "top",
                            21000,
                            3156,
                            "linear",
                            "${hp2}",
                            '119px',
                            '146px'
                        ],
                        [
                            "eid275",
                            "top",
                            30000,
                            921,
                            "linear",
                            "${hp2}",
                            '146px',
                            '24px'
                        ],
                        [
                            "eid274",
                            "height",
                            30000,
                            921,
                            "linear",
                            "${hp2}",
                            '55px',
                            '72px'
                        ],
                        [
                            "eid167",
                            "top",
                            10774,
                            762,
                            "linear",
                            "${hp4}",
                            '224px',
                            '140px'
                        ],
                        [
                            "eid213",
                            "top",
                            11536,
                            9464,
                            "linear",
                            "${hp4}",
                            '140px',
                            '217px'
                        ],
                        [
                            "eid253",
                            "top",
                            21000,
                            3156,
                            "linear",
                            "${hp4}",
                            '217px',
                            '234px'
                        ],
                        [
                            "eid285",
                            "top",
                            31713,
                            719,
                            "linear",
                            "${hp4}",
                            '234px',
                            '173px'
                        ],
                        [
                            "eid149",
                            "opacity",
                            9026,
                            472,
                            "linear",
                            "${Text}",
                            '0',
                            '1'
                        ],
                        [
                            "eid198",
                            "opacity",
                            10774,
                            762,
                            "linear",
                            "${Text}",
                            '1',
                            '0'
                        ],
                        [
                            "eid287",
                            "height",
                            31713,
                            719,
                            "linear",
                            "${hp4}",
                            '37px',
                            '54px'
                        ],
                        [
                            "eid323",
                            "width",
                            28474,
                            526,
                            "linear",
                            "${towe}",
                            '68px',
                            '137px'
                        ],
                        [
                            "eid314",
                            "opacity",
                            37414,
                            1131,
                            "linear",
                            "${covre}",
                            '0',
                            '1'
                        ],
                        [
                            "eid315",
                            "opacity",
                            39477,
                            553,
                            "linear",
                            "${covre}",
                            '1',
                            '0'
                        ],
                        [
                            "eid355",
                            "opacity",
                            48000,
                            1129,
                            "linear",
                            "${covre}",
                            '0',
                            '1'
                        ],
                        [
                            "eid357",
                            "opacity",
                            50000,
                            853,
                            "linear",
                            "${covre}",
                            '1',
                            '0'
                        ],
                        [
                            "eid362",
                            "opacity",
                            50000,
                            853,
                            "linear",
                            "${back}",
                            '1',
                            '0'
                        ],
                        [
                            "eid356",
                            "display",
                            0,
                            0,
                            "linear",
                            "${all}",
                            'none',
                            'block'
                        ],
                        [
                            "eid87",
                            "width",
                            0,
                            0,
                            "linear",
                            "${lid}",
                            '161px',
                            '161px'
                        ],
                        [
                            "eid90",
                            "top",
                            0,
                            0,
                            "linear",
                            "${lid}",
                            '117px',
                            '117px'
                        ],
                        [
                            "eid272",
                            "opacity",
                            26506,
                            992,
                            "linear",
                            "${Text6}",
                            '0',
                            '1'
                        ],
                        [
                            "eid273",
                            "opacity",
                            29000,
                            752,
                            "linear",
                            "${Text6}",
                            '1',
                            '0'
                        ],
                        [
                            "eid139",
                            "opacity",
                            5327,
                            1673,
                            "linear",
                            "${hp4}",
                            '0',
                            '1'
                        ],
                        [
                            "eid142",
                            "opacity",
                            8511,
                            515,
                            "linear",
                            "${hp4}",
                            '1',
                            '0'
                        ],
                        [
                            "eid228",
                            "opacity",
                            13000,
                            0,
                            "linear",
                            "${hp4}",
                            '0',
                            '0'
                        ],
                        [
                            "eid234",
                            "opacity",
                            13471,
                            0,
                            "linear",
                            "${hp4}",
                            '0',
                            '0'
                        ],
                        [
                            "eid246",
                            "opacity",
                            21000,
                            1491,
                            "linear",
                            "${hp4}",
                            '0',
                            '1'
                        ],
                        [
                            "eid301",
                            "opacity",
                            37000,
                            997,
                            "linear",
                            "${hp4}",
                            '1',
                            '0'
                        ],
                        [
                            "eid59",
                            "height",
                            0,
                            0,
                            "linear",
                            "${hydro}",
                            '236px',
                            '236px'
                        ],
                        [
                            "eid109",
                            "height",
                            0,
                            0,
                            "linear",
                            "${back}",
                            '61px',
                            '61px'
                        ],
                        [
                            "eid6",
                            "display",
                            0,
                            0,
                            "linear",
                            "${lid}",
                            'block',
                            'block'
                        ],
                        [
                            "eid173",
                            "top",
                            10774,
                            762,
                            "linear",
                            "${hp3}",
                            '252px',
                            '139px'
                        ],
                        [
                            "eid209",
                            "top",
                            11536,
                            9464,
                            "linear",
                            "${hp3}",
                            '139px',
                            '303px'
                        ],
                        [
                            "eid259",
                            "top",
                            21000,
                            3156,
                            "linear",
                            "${hp3}",
                            '303px',
                            '314px'
                        ],
                        [
                            "eid294",
                            "top",
                            33032,
                            633,
                            "linear",
                            "${hp3}",
                            '314px',
                            '309px'
                        ],
                        [
                            "eid295",
                            "height",
                            33032,
                            633,
                            "linear",
                            "${hp3}",
                            '37px',
                            '50px'
                        ],
                        [
                            "eid367",
                            "top",
                            41489,
                            0,
                            "linear",
                            "${all}",
                            '105px',
                            '105px'
                        ],
                        [
                            "eid84",
                            "height",
                            0,
                            0,
                            "linear",
                            "${lid}",
                            '57px',
                            '57px'
                        ],
                        [
                            "eid137",
                            "opacity",
                            4476,
                            851,
                            "linear",
                            "${hp3}",
                            '0',
                            '1'
                        ],
                        [
                            "eid145",
                            "opacity",
                            8511,
                            515,
                            "linear",
                            "${hp3}",
                            '1',
                            '0'
                        ],
                        [
                            "eid231",
                            "opacity",
                            13000,
                            0,
                            "linear",
                            "${hp3}",
                            '0',
                            '0'
                        ],
                        [
                            "eid240",
                            "opacity",
                            13471,
                            0,
                            "linear",
                            "${hp3}",
                            '0',
                            '0'
                        ],
                        [
                            "eid249",
                            "opacity",
                            21000,
                            1491,
                            "linear",
                            "${hp3}",
                            '0',
                            '1'
                        ],
                        [
                            "eid304",
                            "opacity",
                            37000,
                            997,
                            "linear",
                            "${hp3}",
                            '1',
                            '0'
                        ],
                        [
                            "eid201",
                            "height",
                            16254,
                            1082,
                            "linear",
                            "${thermo2}",
                            '163px',
                            '74px'
                        ],
                        [
                            "eid124",
                            "left",
                            0,
                            0,
                            "linear",
                            "${heatpak}",
                            '247px',
                            '247px'
                        ],
                        [
                            "eid218",
                            "left",
                            20468,
                            532,
                            "linear",
                            "${heatpak}",
                            '247px',
                            '458px'
                        ],
                        [
                            "eid254",
                            "left",
                            21000,
                            3156,
                            "linear",
                            "${heatpak}",
                            '458px',
                            '457px'
                        ],
                        [
                            "eid279",
                            "left",
                            30921,
                            792,
                            "linear",
                            "${heatpak}",
                            '457px',
                            '442px'
                        ],
                        [
                            "eid346",
                            "left",
                            38545,
                            853,
                            "linear",
                            "${heatpak}",
                            '442px',
                            '434px'
                        ],
                        [
                            "eid350",
                            "left",
                            41000,
                            489,
                            "linear",
                            "${heatpak}",
                            '434px',
                            '409px'
                        ],
                        [
                            "eid155",
                            "opacity",
                            10774,
                            1226,
                            "linear",
                            "${thermo2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid363",
                            "opacity",
                            50000,
                            853,
                            "linear",
                            "${thermo2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid141",
                            "opacity",
                            7000,
                            1511,
                            "linear",
                            "${hp5}",
                            '0',
                            '1'
                        ],
                        [
                            "eid144",
                            "opacity",
                            8511,
                            515,
                            "linear",
                            "${hp5}",
                            '1',
                            '0'
                        ],
                        [
                            "eid233",
                            "opacity",
                            13000,
                            0,
                            "linear",
                            "${hp5}",
                            '0',
                            '0'
                        ],
                        [
                            "eid244",
                            "opacity",
                            13471,
                            0,
                            "linear",
                            "${hp5}",
                            '0',
                            '0'
                        ],
                        [
                            "eid251",
                            "opacity",
                            21000,
                            1491,
                            "linear",
                            "${hp5}",
                            '0',
                            '1'
                        ],
                        [
                            "eid306",
                            "opacity",
                            37000,
                            997,
                            "linear",
                            "${hp5}",
                            '1',
                            '0'
                        ],
                        [
                            "eid123",
                            "width",
                            0,
                            0,
                            "linear",
                            "${heatpak}",
                            '55px',
                            '55px'
                        ],
                        [
                            "eid281",
                            "width",
                            30921,
                            792,
                            "linear",
                            "${heatpak}",
                            '55px',
                            '66px'
                        ],
                        [
                            "eid348",
                            "width",
                            38545,
                            853,
                            "linear",
                            "${heatpak}",
                            '66px',
                            '82px'
                        ],
                        [
                            "eid150",
                            "display",
                            9026,
                            0,
                            "linear",
                            "${Text}",
                            'none',
                            'block'
                        ],
                        [
                            "eid5",
                            "display",
                            0,
                            0,
                            "linear",
                            "${hydro}",
                            'block',
                            'block'
                        ],
                        [
                            "eid292",
                            "width",
                            32432,
                            600,
                            "linear",
                            "${hp5}",
                            '115px',
                            '127px'
                        ],
                        [
                            "eid171",
                            "top",
                            10774,
                            762,
                            "linear",
                            "${hp5}",
                            '315px',
                            '231px'
                        ],
                        [
                            "eid211",
                            "top",
                            11536,
                            9464,
                            "linear",
                            "${hp5}",
                            '231px',
                            '177px'
                        ],
                        [
                            "eid263",
                            "top",
                            21000,
                            3156,
                            "linear",
                            "${hp5}",
                            '177px',
                            '224px'
                        ],
                        [
                            "eid289",
                            "top",
                            32432,
                            600,
                            "linear",
                            "${hp5}",
                            '224px',
                            '179px'
                        ],
                        [
                            "eid110",
                            "top",
                            0,
                            0,
                            "linear",
                            "${back}",
                            '126px',
                            '126px'
                        ],
                        [
                            "eid47",
                            "top",
                            0,
                            0,
                            "linear",
                            "${towe}",
                            '105px',
                            '105px'
                        ],
                        [
                            "eid321",
                            "top",
                            28474,
                            526,
                            "linear",
                            "${towe}",
                            '105px',
                            '19px'
                        ],
                        [
                            "eid333",
                            "top",
                            41489,
                            853,
                            "linear",
                            "${towe}",
                            '19px',
                            '24px'
                        ],
                        [
                            "eid334",
                            "top",
                            42342,
                            707,
                            "linear",
                            "${towe}",
                            '24px',
                            '179px'
                        ],
                        [
                            "eid379",
                            "opacity",
                            51864,
                            1136,
                            "linear",
                            "${Text10}",
                            '0',
                            '1'
                        ],
                        [
                            "eid377",
                            "opacity",
                            51864,
                            1136,
                            "linear",
                            "${Text8}",
                            '0',
                            '1'
                        ],
                        [
                            "eid297",
                            "height",
                            33665,
                            843,
                            "linear",
                            "${hp1}",
                            '73px',
                            '84px'
                        ],
                        [
                            "eid340",
                            "opacity",
                            43567,
                            433,
                            "linear",
                            "${Text7}",
                            '0',
                            '1'
                        ],
                        [
                            "eid359",
                            "opacity",
                            50000,
                            853,
                            "linear",
                            "${Text7}",
                            '1',
                            '0'
                        ],
                        [
                            "eid135",
                            "opacity",
                            3000,
                            1476,
                            "linear",
                            "${hp2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid146",
                            "opacity",
                            8511,
                            515,
                            "linear",
                            "${hp2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid232",
                            "opacity",
                            13000,
                            0,
                            "linear",
                            "${hp2}",
                            '0',
                            '0'
                        ],
                        [
                            "eid242",
                            "opacity",
                            13471,
                            0,
                            "linear",
                            "${hp2}",
                            '0',
                            '0'
                        ],
                        [
                            "eid250",
                            "opacity",
                            21000,
                            1491,
                            "linear",
                            "${hp2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid302",
                            "opacity",
                            37000,
                            997,
                            "linear",
                            "${hp2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid174",
                            "left",
                            10774,
                            762,
                            "linear",
                            "${hp1}",
                            '50px',
                            '573px'
                        ],
                        [
                            "eid206",
                            "left",
                            11536,
                            9464,
                            "linear",
                            "${hp1}",
                            '573px',
                            '421px'
                        ],
                        [
                            "eid256",
                            "left",
                            21000,
                            3156,
                            "linear",
                            "${hp1}",
                            '421px',
                            '433px'
                        ],
                        [
                            "eid299",
                            "left",
                            33665,
                            843,
                            "linear",
                            "${hp1}",
                            '433px',
                            '417px'
                        ],
                        [
                            "eid46",
                            "left",
                            0,
                            0,
                            "linear",
                            "${towe}",
                            '640px',
                            '640px'
                        ],
                        [
                            "eid320",
                            "left",
                            28474,
                            526,
                            "linear",
                            "${towe}",
                            '640px',
                            '204px'
                        ],
                        [
                            "eid332",
                            "left",
                            41489,
                            853,
                            "linear",
                            "${towe}",
                            '204px',
                            '373px'
                        ],
                        [
                            "eid335",
                            "left",
                            42342,
                            707,
                            "linear",
                            "${towe}",
                            '373px',
                            '387px'
                        ],
                        [
                            "eid204",
                            "opacity",
                            17336,
                            934,
                            "linear",
                            "${lid}",
                            '1',
                            '0'
                        ],
                        [
                            "eid18",
                            "height",
                            0,
                            0,
                            "linear",
                            "${covre}",
                            '66px',
                            '66px'
                        ],
                        [
                            "eid311",
                            "height",
                            27000,
                            498,
                            "linear",
                            "${covre}",
                            '66px',
                            '93px'
                        ],
                        [
                            "eid300",
                            "width",
                            33665,
                            843,
                            "linear",
                            "${hp1}",
                            '92px',
                            '99px'
                        ],
                        [
                            "eid111",
                            "width",
                            0,
                            0,
                            "linear",
                            "${back}",
                            '160px',
                            '160px'
                        ],
                        [
                            "eid170",
                            "left",
                            10774,
                            762,
                            "linear",
                            "${hp5}",
                            '398px',
                            '742px'
                        ],
                        [
                            "eid210",
                            "left",
                            11536,
                            9464,
                            "linear",
                            "${hp5}",
                            '742px',
                            '427px'
                        ],
                        [
                            "eid262",
                            "left",
                            21000,
                            3156,
                            "linear",
                            "${hp5}",
                            '427px',
                            '421px'
                        ],
                        [
                            "eid290",
                            "left",
                            32432,
                            600,
                            "linear",
                            "${hp5}",
                            '421px',
                            '403px'
                        ],
                        [
                            "eid172",
                            "left",
                            10774,
                            762,
                            "linear",
                            "${hp3}",
                            '58px',
                            '581px'
                        ],
                        [
                            "eid208",
                            "left",
                            11536,
                            9464,
                            "linear",
                            "${hp3}",
                            '581px',
                            '39px'
                        ],
                        [
                            "eid258",
                            "left",
                            21000,
                            3156,
                            "linear",
                            "${hp3}",
                            '39px',
                            '47px'
                        ],
                        [
                            "eid293",
                            "left",
                            33032,
                            633,
                            "linear",
                            "${hp3}",
                            '47px',
                            '28px'
                        ],
                        [
                            "eid1",
                            "display",
                            0,
                            0,
                            "linear",
                            "${heatpak}",
                            'block',
                            'block'
                        ],
                        [
                            "eid361",
                            "opacity",
                            50000,
                            853,
                            "linear",
                            "${hydro}",
                            '1',
                            '0'
                        ],
                        [
                            "eid122",
                            "height",
                            0,
                            0,
                            "linear",
                            "${heatpak}",
                            '74px',
                            '74px'
                        ],
                        [
                            "eid280",
                            "height",
                            30921,
                            792,
                            "linear",
                            "${heatpak}",
                            '74px',
                            '93px'
                        ],
                        [
                            "eid347",
                            "height",
                            38545,
                            853,
                            "linear",
                            "${heatpak}",
                            '93px',
                            '106px'
                        ],
                        [
                            "eid168",
                            "left",
                            10774,
                            762,
                            "linear",
                            "${hp2}",
                            '421px',
                            '787px'
                        ],
                        [
                            "eid191",
                            "left",
                            11536,
                            3169,
                            "linear",
                            "${hp2}",
                            '787px',
                            '842px'
                        ],
                        [
                            "eid214",
                            "left",
                            14705,
                            6295,
                            "linear",
                            "${hp2}",
                            '842px',
                            '69px'
                        ],
                        [
                            "eid260",
                            "left",
                            21000,
                            3156,
                            "linear",
                            "${hp2}",
                            '69px',
                            '47px'
                        ],
                        [
                            "eid277",
                            "left",
                            30000,
                            921,
                            "linear",
                            "${hp2}",
                            '47px',
                            '28px'
                        ],
                        [
                            "eid175",
                            "top",
                            10774,
                            762,
                            "linear",
                            "${hp1}",
                            '101px',
                            '-12px'
                        ],
                        [
                            "eid207",
                            "top",
                            11536,
                            9464,
                            "linear",
                            "${hp1}",
                            '-12px',
                            '260px'
                        ],
                        [
                            "eid257",
                            "top",
                            21000,
                            3156,
                            "linear",
                            "${hp1}",
                            '260px',
                            '285px'
                        ],
                        [
                            "eid298",
                            "top",
                            33665,
                            843,
                            "linear",
                            "${hp1}",
                            '285px',
                            '285px'
                        ],
                        [
                            "eid20",
                            "width",
                            0,
                            0,
                            "linear",
                            "${covre}",
                            '99px',
                            '99px'
                        ],
                        [
                            "eid312",
                            "width",
                            27000,
                            498,
                            "linear",
                            "${covre}",
                            '99px',
                            '140px'
                        ],
                        [
                            "eid310",
                            "top",
                            27000,
                            498,
                            "linear",
                            "${covre}",
                            '195px',
                            '12px'
                        ],
                        [
                            "eid288",
                            "width",
                            31713,
                            719,
                            "linear",
                            "${hp4}",
                            '36px',
                            '44px'
                        ],
                        [
                            "eid91",
                            "left",
                            0,
                            0,
                            "linear",
                            "${lid}",
                            '192px',
                            '192px'
                        ],
                        [
                            "eid202",
                            "width",
                            16254,
                            1082,
                            "linear",
                            "${thermo2}",
                            '45px',
                            '20px'
                        ],
                        [
                            "eid375",
                            "opacity",
                            51864,
                            1136,
                            "linear",
                            "${Text4}",
                            '0',
                            '1'
                        ],
                        [
                            "eid322",
                            "height",
                            28474,
                            526,
                            "linear",
                            "${towe}",
                            '41px',
                            '98px'
                        ],
                        [
                            "eid365",
                            "opacity",
                            51864,
                            1136,
                            "linear",
                            "${all}",
                            '0',
                            '1'
                        ],
                        [
                            "eid325",
                            "opacity",
                            39398,
                            632,
                            "linear",
                            "${towe}",
                            '0',
                            '1'
                        ],
                        [
                            "eid360",
                            "opacity",
                            50000,
                            853,
                            "linear",
                            "${towe}",
                            '1',
                            '0'
                        ],
                        [
                            "eid200",
                            "top",
                            16254,
                            1082,
                            "linear",
                            "${thermo2}",
                            '174px',
                            '9px'
                        ],
                        [
                            "eid205",
                            "top",
                            18270,
                            1730,
                            "linear",
                            "${thermo2}",
                            '9px',
                            '187px'
                        ],
                            [ "eid368", "trigger", 0, function executeMediaFunction(e, data) { this._executeMediaAction(e, data); }, ['play', '${media12}', [] ] ]
                    ]
                }
            }
        };

    AdobeEdge.registerCompositionDefn(compId, symbols, fonts, scripts, resources, opts);

    if (!window.edge_authoring_mode) AdobeEdge.getComposition(compId).load("hydro_edgeActions.js");
})("EDGE-35485452");
