/*jslint */
/*global AdobeEdge: false, window: false, document: false, console:false, alert: false */
(function (compId) {

    "use strict";
    var im='images/',
        aud='media/',
        vid='media/',
        js='js/',
        fonts = {
        },
        opts = {
            'gAudioPreloadPreference': 'auto',
            'gVideoPreloadPreference': 'auto'
        },
        resources = [
        ],
        scripts = [
        ],
        symbols = {
            "stage": {
                version: "6.0.0",
                minimumCompatibleVersion: "5.0.0",
                build: "6.0.0.400",
                scaleToFit: "none",
                centerStage: "none",
                resizeInstances: false,
                content: {
                    dom: [
                        {
                            id: 'cell',
                            type: 'image',
                            rect: ['92px', '62px', '383px', '279px', 'auto', 'auto'],
                            fill: ["rgba(0,0,0,0)",im+"cell.svg",'0px','0px']
                        },
                        {
                            id: 'o2',
                            display: 'block',
                            type: 'image',
                            rect: ['257px', '7px', '35px', '42px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"o2.svg",'0px','0px']
                        },
                        {
                            id: 'waste',
                            display: 'block',
                            type: 'image',
                            rect: ['339px', '198px', '38px', '52px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"waste.svg",'0px','0px']
                        },
                        {
                            id: 'heal',
                            display: 'block',
                            type: 'image',
                            rect: ['251px', '174px', '47px', '47px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"heal.svg",'0px','0px']
                        },
                        {
                            id: 'heal2',
                            type: 'image',
                            rect: ['251px', '174px', '47px', '47px', 'auto', 'auto'],
                            fill: ["rgba(0,0,0,0)",im+"heal2.svg",'0px','0px']
                        },
                        {
                            id: 'heal3',
                            type: 'image',
                            rect: ['251px', '174px', '47px', '47px', 'auto', 'auto'],
                            fill: ["rgba(0,0,0,0)",im+"heal3.svg",'0px','0px']
                        },
                        {
                            id: 'heal4',
                            type: 'image',
                            rect: ['251px', '174px', '47px', '47px', 'auto', 'auto'],
                            fill: ["rgba(0,0,0,0)",im+"heal4.svg",'0px','0px']
                        },
                        {
                            id: 'burg',
                            display: 'block',
                            type: 'image',
                            rect: ['21px', '186px', '53px', '28px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"burg.svg",'0px','0px']
                        },
                        {
                            id: 'cell2',
                            display: 'none',
                            type: 'audio',
                            tag: 'audio',
                            rect: ['0', '0', '320px', '45px', 'auto', 'auto'],
                            source: [aud+"cell.wav"],
                            preload: 'auto'
                        },
                        {
                            id: 'purple',
                            display: 'none',
                            type: 'image',
                            rect: ['470px', '243px', '35px', '138px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"purple.svg",'0px','0px']
                        },
                        {
                            id: 'blue',
                            display: 'none',
                            type: 'image',
                            rect: ['470px', '243px', '35px', '138px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"blue.svg",'0px','0px']
                        },
                        {
                            id: 'cyan',
                            display: 'none',
                            type: 'image',
                            rect: ['470px', '243px', '35px', '138px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"cyan.svg",'0px','0px']
                        },
                        {
                            id: 'olive',
                            display: 'none',
                            type: 'image',
                            rect: ['470px', '243px', '35px', '138px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"olive.svg",'0px','0px']
                        },
                        {
                            id: 'lime',
                            display: 'none',
                            type: 'image',
                            rect: ['470px', '243px', '35px', '138px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"lime.svg",'0px','0px']
                        },
                        {
                            id: 'yello',
                            display: 'none',
                            type: 'image',
                            rect: ['470px', '243px', '35px', '138px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"yello.svg",'0px','0px']
                        },
                        {
                            id: 'orange',
                            display: 'none',
                            type: 'image',
                            rect: ['470px', '243px', '35px', '138px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"orange.svg",'0px','0px']
                        },
                        {
                            id: 'bloodorange',
                            display: 'none',
                            type: 'image',
                            rect: ['470px', '243px', '35px', '138px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"bloodorange.svg",'0px','0px']
                        },
                        {
                            id: 'red',
                            display: 'none',
                            type: 'image',
                            rect: ['470px', '243px', '35px', '138px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"red.svg",'0px','0px']
                        },
                        {
                            id: 'brick',
                            display: 'none',
                            type: 'image',
                            rect: ['470px', '243px', '35px', '138px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"brick.svg",'0px','0px']
                        },
                        {
                            id: 'cell22',
                            display: 'none',
                            type: 'audio',
                            tag: 'audio',
                            rect: ['0', '0', '320px', '45px', 'auto', 'auto'],
                            source: [aud+"cell2.wav"],
                            preload: 'auto'
                        }
                    ],
                    style: {
                        '${Stage}': {
                            isStage: true,
                            rect: [undefined, undefined, '550px', '400px'],
                            overflow: 'hidden',
                            fill: ["rgba(255,255,255,1)"]
                        }
                    }
                },
                timeline: {
                    duration: 31199.637,
                    autoPlay: true,
                    data: [
                        [
                            "eid188",
                            "left",
                            0,
                            0,
                            "linear",
                            "${red}",
                            '470px',
                            '470px'
                        ],
                        [
                            "eid107",
                            "opacity",
                            6507,
                            129,
                            "linear",
                            "${orange}",
                            '0',
                            '1'
                        ],
                        [
                            "eid8",
                            "display",
                            0,
                            0,
                            "linear",
                            "${cyan}",
                            'none',
                            'block'
                        ],
                        [
                            "eid180",
                            "left",
                            0,
                            0,
                            "linear",
                            "${cyan}",
                            '470px',
                            '470px'
                        ],
                        [
                            "eid190",
                            "left",
                            0,
                            0,
                            "linear",
                            "${orange}",
                            '470px',
                            '470px'
                        ],
                        [
                            "eid119",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${o2}",
                            '0',
                            '0'
                        ],
                        [
                            "eid205",
                            "opacity",
                            12248,
                            735,
                            "linear",
                            "${o2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid207",
                            "opacity",
                            13500,
                            664,
                            "linear",
                            "${o2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid238",
                            "opacity",
                            14500,
                            735,
                            "linear",
                            "${o2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid239",
                            "opacity",
                            15752,
                            664,
                            "linear",
                            "${o2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid242",
                            "opacity",
                            16752,
                            735,
                            "linear",
                            "${o2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid243",
                            "opacity",
                            18004,
                            664,
                            "linear",
                            "${o2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid246",
                            "opacity",
                            19004,
                            735,
                            "linear",
                            "${o2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid247",
                            "opacity",
                            20256,
                            664,
                            "linear",
                            "${o2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid250",
                            "opacity",
                            21256,
                            735,
                            "linear",
                            "${o2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid251",
                            "opacity",
                            22508,
                            664,
                            "linear",
                            "${o2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid347",
                            "left",
                            0,
                            0,
                            "linear",
                            "${heal2}",
                            '251px',
                            '251px'
                        ],
                        [
                            "eid360",
                            "left",
                            25193,
                            1224,
                            "linear",
                            "${heal2}",
                            '251px',
                            '103px'
                        ],
                        [
                            "eid361",
                            "left",
                            27500,
                            108,
                            "linear",
                            "${heal2}",
                            '103px',
                            '251px'
                        ],
                        [
                            "eid386",
                            "left",
                            28297,
                            1224,
                            "linear",
                            "${heal2}",
                            '251px',
                            '103px'
                        ],
                        [
                            "eid387",
                            "left",
                            30604,
                            108,
                            "linear",
                            "${heal2}",
                            '103px',
                            '251px'
                        ],
                        [
                            "eid106",
                            "opacity",
                            6290,
                            217,
                            "linear",
                            "${yello}",
                            '0',
                            '1'
                        ],
                        [
                            "eid103",
                            "opacity",
                            5758,
                            177,
                            "linear",
                            "${cyan}",
                            '0',
                            '1'
                        ],
                        [
                            "eid104",
                            "opacity",
                            5935,
                            211,
                            "linear",
                            "${olive}",
                            '0',
                            '1'
                        ],
                        [
                            "eid120",
                            "height",
                            2000,
                            1486,
                            "linear",
                            "${cell}",
                            '234px',
                            '272px'
                        ],
                        [
                            "eid406",
                            "height",
                            26417,
                            202,
                            "linear",
                            "${cell}",
                            '272px',
                            '279px'
                        ],
                        [
                            "eid413",
                            "height",
                            26619,
                            131,
                            "linear",
                            "${cell}",
                            '279px',
                            '272px'
                        ],
                        [
                            "eid416",
                            "height",
                            29521,
                            202,
                            "linear",
                            "${cell}",
                            '272px',
                            '279px'
                        ],
                        [
                            "eid417",
                            "height",
                            29723,
                            131,
                            "linear",
                            "${cell}",
                            '279px',
                            '272px'
                        ],
                        [
                            "eid6",
                            "display",
                            0,
                            0,
                            "linear",
                            "${lime}",
                            'none',
                            'block'
                        ],
                        [
                            "eid146",
                            "width",
                            0,
                            0,
                            "linear",
                            "${purple}",
                            '35px',
                            '35px'
                        ],
                        [
                            "eid181",
                            "top",
                            0,
                            0,
                            "linear",
                            "${cyan}",
                            '243px',
                            '243px'
                        ],
                        [
                            "eid168",
                            "height",
                            0,
                            0,
                            "linear",
                            "${orange}",
                            '138px',
                            '138px'
                        ],
                        [
                            "eid152",
                            "width",
                            0,
                            0,
                            "linear",
                            "${olive}",
                            '35px',
                            '35px'
                        ],
                        [
                            "eid184",
                            "left",
                            0,
                            0,
                            "linear",
                            "${brick}",
                            '470px',
                            '470px'
                        ],
                        [
                            "eid164",
                            "width",
                            0,
                            0,
                            "linear",
                            "${bloodorange}",
                            '35px',
                            '35px'
                        ],
                        [
                            "eid7",
                            "display",
                            0,
                            0,
                            "linear",
                            "${olive}",
                            'none',
                            'block'
                        ],
                        [
                            "eid186",
                            "left",
                            0,
                            0,
                            "linear",
                            "${bloodorange}",
                            '470px',
                            '470px'
                        ],
                        [
                            "eid170",
                            "width",
                            0,
                            0,
                            "linear",
                            "${orange}",
                            '35px',
                            '35px'
                        ],
                        [
                            "eid391",
                            "top",
                            0,
                            0,
                            "linear",
                            "${heal4}",
                            '174px',
                            '174px'
                        ],
                        [
                            "eid392",
                            "top",
                            25193,
                            1224,
                            "linear",
                            "${heal4}",
                            '174px',
                            '38px'
                        ],
                        [
                            "eid393",
                            "top",
                            27500,
                            108,
                            "linear",
                            "${heal4}",
                            '38px',
                            '174px'
                        ],
                        [
                            "eid398",
                            "top",
                            28297,
                            1224,
                            "linear",
                            "${heal4}",
                            '174px',
                            '38px'
                        ],
                        [
                            "eid399",
                            "top",
                            30604,
                            108,
                            "linear",
                            "${heal4}",
                            '38px',
                            '174px'
                        ],
                        [
                            "eid156",
                            "height",
                            0,
                            0,
                            "linear",
                            "${lime}",
                            '138px',
                            '138px'
                        ],
                        [
                            "eid177",
                            "top",
                            0,
                            0,
                            "linear",
                            "${yello}",
                            '243px',
                            '243px'
                        ],
                        [
                            "eid390",
                            "left",
                            0,
                            0,
                            "linear",
                            "${heal4}",
                            '251px',
                            '251px'
                        ],
                        [
                            "eid396",
                            "left",
                            25193,
                            1224,
                            "linear",
                            "${heal4}",
                            '251px',
                            '275px'
                        ],
                        [
                            "eid397",
                            "left",
                            27500,
                            108,
                            "linear",
                            "${heal4}",
                            '275px',
                            '251px'
                        ],
                        [
                            "eid402",
                            "left",
                            28297,
                            1224,
                            "linear",
                            "${heal4}",
                            '251px',
                            '275px'
                        ],
                        [
                            "eid403",
                            "left",
                            30604,
                            108,
                            "linear",
                            "${heal4}",
                            '275px',
                            '251px'
                        ],
                        [
                            "eid3",
                            "display",
                            0,
                            0,
                            "linear",
                            "${bloodorange}",
                            'none',
                            'block'
                        ],
                        [
                            "eid185",
                            "top",
                            0,
                            0,
                            "linear",
                            "${brick}",
                            '243px',
                            '243px'
                        ],
                        [
                            "eid149",
                            "width",
                            0,
                            0,
                            "linear",
                            "${yello}",
                            '35px',
                            '35px'
                        ],
                        [
                            "eid349",
                            "top",
                            0,
                            0,
                            "linear",
                            "${heal2}",
                            '174px',
                            '174px'
                        ],
                        [
                            "eid352",
                            "top",
                            25193,
                            1224,
                            "linear",
                            "${heal2}",
                            '174px',
                            '167px'
                        ],
                        [
                            "eid353",
                            "top",
                            27500,
                            108,
                            "linear",
                            "${heal2}",
                            '167px',
                            '174px'
                        ],
                        [
                            "eid382",
                            "top",
                            28297,
                            1224,
                            "linear",
                            "${heal2}",
                            '174px',
                            '167px'
                        ],
                        [
                            "eid383",
                            "top",
                            30604,
                            108,
                            "linear",
                            "${heal2}",
                            '167px',
                            '174px'
                        ],
                        [
                            "eid9",
                            "display",
                            0,
                            0,
                            "linear",
                            "${blue}",
                            'none',
                            'block'
                        ],
                        [
                            "eid173",
                            "width",
                            0,
                            0,
                            "linear",
                            "${blue}",
                            '35px',
                            '35px'
                        ],
                        [
                            "eid110",
                            "opacity",
                            6965,
                            169,
                            "linear",
                            "${brick}",
                            '0',
                            '1'
                        ],
                        [
                            "eid350",
                            "left",
                            0,
                            0,
                            "linear",
                            "${heal3}",
                            '251px',
                            '251px'
                        ],
                        [
                            "eid372",
                            "left",
                            25193,
                            1224,
                            "linear",
                            "${heal3}",
                            '251px',
                            '405px'
                        ],
                        [
                            "eid373",
                            "left",
                            27500,
                            108,
                            "linear",
                            "${heal3}",
                            '405px',
                            '251px'
                        ],
                        [
                            "eid380",
                            "left",
                            28297,
                            1224,
                            "linear",
                            "${heal3}",
                            '251px',
                            '405px'
                        ],
                        [
                            "eid381",
                            "left",
                            30604,
                            108,
                            "linear",
                            "${heal3}",
                            '405px',
                            '251px'
                        ],
                        [
                            "eid179",
                            "top",
                            0,
                            0,
                            "linear",
                            "${olive}",
                            '243px',
                            '243px'
                        ],
                        [
                            "eid114",
                            "display",
                            0,
                            0,
                            "linear",
                            "${waste}",
                            'block',
                            'block'
                        ],
                        [
                            "eid183",
                            "top",
                            0,
                            0,
                            "linear",
                            "${lime}",
                            '243px',
                            '243px'
                        ],
                        [
                            "eid305",
                            "left",
                            20216,
                            1040,
                            "linear",
                            "${burg}",
                            '21px',
                            '160px'
                        ],
                        [
                            "eid308",
                            "left",
                            21799,
                            192,
                            "linear",
                            "${burg}",
                            '160px',
                            '21px'
                        ],
                        [
                            "eid314",
                            "left",
                            22468,
                            1040,
                            "linear",
                            "${burg}",
                            '21px',
                            '160px'
                        ],
                        [
                            "eid315",
                            "left",
                            24051,
                            192,
                            "linear",
                            "${burg}",
                            '160px',
                            '21px'
                        ],
                        [
                            "eid158",
                            "width",
                            0,
                            0,
                            "linear",
                            "${lime}",
                            '35px',
                            '35px'
                        ],
                        [
                            "eid178",
                            "left",
                            0,
                            0,
                            "linear",
                            "${olive}",
                            '470px',
                            '470px'
                        ],
                        [
                            "eid175",
                            "top",
                            0,
                            0,
                            "linear",
                            "${purple}",
                            '243px',
                            '243px'
                        ],
                        [
                            "eid4",
                            "display",
                            0,
                            0,
                            "linear",
                            "${orange}",
                            'none',
                            'block'
                        ],
                        [
                            "eid162",
                            "height",
                            0,
                            0,
                            "linear",
                            "${bloodorange}",
                            '138px',
                            '138px'
                        ],
                        [
                            "eid112",
                            "display",
                            0,
                            0,
                            "linear",
                            "${burg}",
                            'block',
                            'block'
                        ],
                        [
                            "eid192",
                            "left",
                            0,
                            0,
                            "linear",
                            "${blue}",
                            '470px',
                            '470px'
                        ],
                        [
                            "eid161",
                            "width",
                            0,
                            0,
                            "linear",
                            "${brick}",
                            '35px',
                            '35px'
                        ],
                        [
                            "eid10",
                            "display",
                            0,
                            0,
                            "linear",
                            "${purple}",
                            'none',
                            'block'
                        ],
                        [
                            "eid159",
                            "height",
                            0,
                            0,
                            "linear",
                            "${brick}",
                            '138px',
                            '138px'
                        ],
                        [
                            "eid117",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${burg}",
                            '0',
                            '0'
                        ],
                        [
                            "eid304",
                            "opacity",
                            19739,
                            477,
                            "linear",
                            "${burg}",
                            '0',
                            '1'
                        ],
                        [
                            "eid307",
                            "opacity",
                            21256,
                            543,
                            "linear",
                            "${burg}",
                            '1',
                            '0'
                        ],
                        [
                            "eid312",
                            "opacity",
                            21991,
                            477,
                            "linear",
                            "${burg}",
                            '0',
                            '1'
                        ],
                        [
                            "eid313",
                            "opacity",
                            23508,
                            543,
                            "linear",
                            "${burg}",
                            '1',
                            '0'
                        ],
                        [
                            "eid368",
                            "opacity",
                            24504,
                            689,
                            "linear",
                            "${heal3}",
                            '0',
                            '1'
                        ],
                        [
                            "eid369",
                            "opacity",
                            26495,
                            1005,
                            "linear",
                            "${heal3}",
                            '1',
                            '0'
                        ],
                        [
                            "eid378",
                            "opacity",
                            27608,
                            689,
                            "linear",
                            "${heal3}",
                            '0',
                            '1'
                        ],
                        [
                            "eid379",
                            "opacity",
                            29599,
                            1005,
                            "linear",
                            "${heal3}",
                            '1',
                            '0'
                        ],
                        [
                            "eid193",
                            "top",
                            0,
                            0,
                            "linear",
                            "${blue}",
                            '243px',
                            '243px'
                        ],
                        [
                            "eid118",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${waste}",
                            '0',
                            '0'
                        ],
                        [
                            "eid272",
                            "opacity",
                            18004,
                            596,
                            "linear",
                            "${waste}",
                            '0',
                            '1'
                        ],
                        [
                            "eid277",
                            "opacity",
                            19739,
                            261,
                            "linear",
                            "${waste}",
                            '1',
                            '0'
                        ],
                        [
                            "eid282",
                            "opacity",
                            20256,
                            596,
                            "linear",
                            "${waste}",
                            '0',
                            '1'
                        ],
                        [
                            "eid283",
                            "opacity",
                            21991,
                            261,
                            "linear",
                            "${waste}",
                            '1',
                            '0'
                        ],
                        [
                            "eid288",
                            "opacity",
                            22508,
                            596,
                            "linear",
                            "${waste}",
                            '0',
                            '1'
                        ],
                        [
                            "eid289",
                            "opacity",
                            24243,
                            261,
                            "linear",
                            "${waste}",
                            '1',
                            '0'
                        ],
                        [
                            "eid150",
                            "height",
                            0,
                            0,
                            "linear",
                            "${olive}",
                            '138px',
                            '138px'
                        ],
                        [
                            "eid351",
                            "top",
                            0,
                            0,
                            "linear",
                            "${heal3}",
                            '174px',
                            '174px'
                        ],
                        [
                            "eid364",
                            "top",
                            25193,
                            1224,
                            "linear",
                            "${heal3}",
                            '174px',
                            '198px'
                        ],
                        [
                            "eid365",
                            "top",
                            27500,
                            108,
                            "linear",
                            "${heal3}",
                            '198px',
                            '174px'
                        ],
                        [
                            "eid376",
                            "top",
                            28297,
                            1224,
                            "linear",
                            "${heal3}",
                            '174px',
                            '198px'
                        ],
                        [
                            "eid377",
                            "top",
                            30604,
                            108,
                            "linear",
                            "${heal3}",
                            '198px',
                            '174px'
                        ],
                        [
                            "eid102",
                            "opacity",
                            5500,
                            258,
                            "linear",
                            "${blue}",
                            '0',
                            '1'
                        ],
                        [
                            "eid336",
                            "left",
                            25193,
                            1224,
                            "linear",
                            "${heal}",
                            '251px',
                            '245px'
                        ],
                        [
                            "eid339",
                            "left",
                            27500,
                            108,
                            "linear",
                            "${heal}",
                            '245px',
                            '251px'
                        ],
                        [
                            "eid345",
                            "left",
                            28297,
                            1224,
                            "linear",
                            "${heal}",
                            '251px',
                            '245px'
                        ],
                        [
                            "eid346",
                            "left",
                            30604,
                            108,
                            "linear",
                            "${heal}",
                            '245px',
                            '251px'
                        ],
                        [
                            "eid182",
                            "left",
                            0,
                            0,
                            "linear",
                            "${lime}",
                            '470px',
                            '470px'
                        ],
                        [
                            "eid105",
                            "opacity",
                            6146,
                            144,
                            "linear",
                            "${lime}",
                            '0',
                            '1'
                        ],
                        [
                            "eid334",
                            "top",
                            0,
                            0,
                            "linear",
                            "${heal}",
                            '174px',
                            '174px'
                        ],
                        [
                            "eid337",
                            "top",
                            25193,
                            1224,
                            "linear",
                            "${heal}",
                            '174px',
                            '299px'
                        ],
                        [
                            "eid340",
                            "top",
                            27500,
                            108,
                            "linear",
                            "${heal}",
                            '299px',
                            '174px'
                        ],
                        [
                            "eid341",
                            "top",
                            28297,
                            1224,
                            "linear",
                            "${heal}",
                            '174px',
                            '299px'
                        ],
                        [
                            "eid342",
                            "top",
                            30604,
                            108,
                            "linear",
                            "${heal}",
                            '299px',
                            '174px'
                        ],
                        [
                            "eid123",
                            "width",
                            2000,
                            1486,
                            "linear",
                            "${cell}",
                            '315px',
                            '366px'
                        ],
                        [
                            "eid407",
                            "width",
                            26417,
                            202,
                            "linear",
                            "${cell}",
                            '366px',
                            '372px'
                        ],
                        [
                            "eid412",
                            "width",
                            26619,
                            131,
                            "linear",
                            "${cell}",
                            '372px',
                            '366px'
                        ],
                        [
                            "eid420",
                            "width",
                            29521,
                            202,
                            "linear",
                            "${cell}",
                            '366px',
                            '372px'
                        ],
                        [
                            "eid421",
                            "width",
                            29723,
                            131,
                            "linear",
                            "${cell}",
                            '372px',
                            '366px'
                        ],
                        [
                            "eid121",
                            "top",
                            2000,
                            1486,
                            "linear",
                            "${cell}",
                            '83px',
                            '62px'
                        ],
                        [
                            "eid408",
                            "top",
                            26417,
                            202,
                            "linear",
                            "${cell}",
                            '62px',
                            '57px'
                        ],
                        [
                            "eid411",
                            "top",
                            26619,
                            131,
                            "linear",
                            "${cell}",
                            '57px',
                            '62px'
                        ],
                        [
                            "eid414",
                            "top",
                            29521,
                            202,
                            "linear",
                            "${cell}",
                            '62px',
                            '57px'
                        ],
                        [
                            "eid415",
                            "top",
                            29723,
                            131,
                            "linear",
                            "${cell}",
                            '57px',
                            '62px'
                        ],
                        [
                            "eid394",
                            "opacity",
                            24504,
                            689,
                            "linear",
                            "${heal4}",
                            '0',
                            '1'
                        ],
                        [
                            "eid395",
                            "opacity",
                            26495,
                            1005,
                            "linear",
                            "${heal4}",
                            '1',
                            '0'
                        ],
                        [
                            "eid400",
                            "opacity",
                            27608,
                            689,
                            "linear",
                            "${heal4}",
                            '0',
                            '1'
                        ],
                        [
                            "eid401",
                            "opacity",
                            29599,
                            1005,
                            "linear",
                            "${heal4}",
                            '1',
                            '0'
                        ],
                        [
                            "eid11",
                            "opacity",
                            5253,
                            247,
                            "linear",
                            "${purple}",
                            '0',
                            '1'
                        ],
                        [
                            "eid171",
                            "height",
                            0,
                            0,
                            "linear",
                            "${blue}",
                            '138px',
                            '138px'
                        ],
                        [
                            "eid2",
                            "display",
                            0,
                            0,
                            "linear",
                            "${red}",
                            'none',
                            'block'
                        ],
                        [
                            "eid206",
                            "top",
                            12983,
                            517,
                            "linear",
                            "${o2}",
                            '7px',
                            '99px'
                        ],
                        [
                            "eid235",
                            "top",
                            14164,
                            336,
                            "linear",
                            "${o2}",
                            '99px',
                            '7px'
                        ],
                        [
                            "eid236",
                            "top",
                            15235,
                            517,
                            "linear",
                            "${o2}",
                            '7px',
                            '99px'
                        ],
                        [
                            "eid237",
                            "top",
                            16416,
                            336,
                            "linear",
                            "${o2}",
                            '99px',
                            '7px'
                        ],
                        [
                            "eid240",
                            "top",
                            17487,
                            517,
                            "linear",
                            "${o2}",
                            '7px',
                            '99px'
                        ],
                        [
                            "eid241",
                            "top",
                            18668,
                            336,
                            "linear",
                            "${o2}",
                            '99px',
                            '7px'
                        ],
                        [
                            "eid244",
                            "top",
                            19739,
                            517,
                            "linear",
                            "${o2}",
                            '7px',
                            '99px'
                        ],
                        [
                            "eid245",
                            "top",
                            20920,
                            336,
                            "linear",
                            "${o2}",
                            '99px',
                            '7px'
                        ],
                        [
                            "eid248",
                            "top",
                            21991,
                            517,
                            "linear",
                            "${o2}",
                            '7px',
                            '99px'
                        ],
                        [
                            "eid249",
                            "top",
                            23172,
                            336,
                            "linear",
                            "${o2}",
                            '99px',
                            '7px'
                        ],
                        [
                            "eid122",
                            "left",
                            2000,
                            1486,
                            "linear",
                            "${cell}",
                            '117px',
                            '92px'
                        ],
                        [
                            "eid409",
                            "left",
                            26417,
                            202,
                            "linear",
                            "${cell}",
                            '92px',
                            '90px'
                        ],
                        [
                            "eid410",
                            "left",
                            26619,
                            131,
                            "linear",
                            "${cell}",
                            '90px',
                            '92px'
                        ],
                        [
                            "eid418",
                            "left",
                            29521,
                            202,
                            "linear",
                            "${cell}",
                            '92px',
                            '90px'
                        ],
                        [
                            "eid419",
                            "left",
                            29723,
                            131,
                            "linear",
                            "${cell}",
                            '90px',
                            '92px'
                        ],
                        [
                            "eid306",
                            "top",
                            20216,
                            1040,
                            "linear",
                            "${burg}",
                            '186px',
                            '172px'
                        ],
                        [
                            "eid309",
                            "top",
                            21799,
                            192,
                            "linear",
                            "${burg}",
                            '172px',
                            '186px'
                        ],
                        [
                            "eid310",
                            "top",
                            22468,
                            1040,
                            "linear",
                            "${burg}",
                            '186px',
                            '172px'
                        ],
                        [
                            "eid311",
                            "top",
                            24051,
                            192,
                            "linear",
                            "${burg}",
                            '172px',
                            '186px'
                        ],
                        [
                            "eid356",
                            "opacity",
                            24504,
                            689,
                            "linear",
                            "${heal2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid357",
                            "opacity",
                            26495,
                            1005,
                            "linear",
                            "${heal2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid384",
                            "opacity",
                            27608,
                            689,
                            "linear",
                            "${heal2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid385",
                            "opacity",
                            29599,
                            1005,
                            "linear",
                            "${heal2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid271",
                            "top",
                            5253,
                            0,
                            "linear",
                            "${waste}",
                            '198px',
                            '198px'
                        ],
                        [
                            "eid276",
                            "top",
                            18668,
                            1071,
                            "linear",
                            "${waste}",
                            '198px',
                            '277px'
                        ],
                        [
                            "eid279",
                            "top",
                            20000,
                            256,
                            "linear",
                            "${waste}",
                            '277px',
                            '198px'
                        ],
                        [
                            "eid280",
                            "top",
                            20920,
                            1071,
                            "linear",
                            "${waste}",
                            '198px',
                            '277px'
                        ],
                        [
                            "eid281",
                            "top",
                            22252,
                            256,
                            "linear",
                            "${waste}",
                            '277px',
                            '198px'
                        ],
                        [
                            "eid286",
                            "top",
                            23172,
                            1071,
                            "linear",
                            "${waste}",
                            '198px',
                            '277px'
                        ],
                        [
                            "eid287",
                            "top",
                            24504,
                            256,
                            "linear",
                            "${waste}",
                            '277px',
                            '198px'
                        ],
                        [
                            "eid116",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${heal}",
                            '0',
                            '0'
                        ],
                        [
                            "eid335",
                            "opacity",
                            24504,
                            689,
                            "linear",
                            "${heal}",
                            '0',
                            '1'
                        ],
                        [
                            "eid338",
                            "opacity",
                            26495,
                            1005,
                            "linear",
                            "${heal}",
                            '1',
                            '0'
                        ],
                        [
                            "eid343",
                            "opacity",
                            27608,
                            689,
                            "linear",
                            "${heal}",
                            '0',
                            '1'
                        ],
                        [
                            "eid344",
                            "opacity",
                            29599,
                            1005,
                            "linear",
                            "${heal}",
                            '1',
                            '0'
                        ],
                        [
                            "eid1",
                            "display",
                            0,
                            0,
                            "linear",
                            "${brick}",
                            'none',
                            'block'
                        ],
                        [
                            "eid176",
                            "left",
                            0,
                            0,
                            "linear",
                            "${yello}",
                            '470px',
                            '470px'
                        ],
                        [
                            "eid165",
                            "height",
                            0,
                            0,
                            "linear",
                            "${red}",
                            '138px',
                            '138px'
                        ],
                        [
                            "eid108",
                            "opacity",
                            6636,
                            149,
                            "linear",
                            "${bloodorange}",
                            '0',
                            '1'
                        ],
                        [
                            "eid187",
                            "top",
                            0,
                            0,
                            "linear",
                            "${bloodorange}",
                            '243px',
                            '243px'
                        ],
                        [
                            "eid113",
                            "display",
                            0,
                            0,
                            "linear",
                            "${o2}",
                            'block',
                            'block'
                        ],
                        [
                            "eid189",
                            "top",
                            0,
                            0,
                            "linear",
                            "${red}",
                            '243px',
                            '243px'
                        ],
                        [
                            "eid144",
                            "height",
                            0,
                            0,
                            "linear",
                            "${purple}",
                            '138px',
                            '138px'
                        ],
                        [
                            "eid191",
                            "top",
                            0,
                            0,
                            "linear",
                            "${orange}",
                            '243px',
                            '243px'
                        ],
                        [
                            "eid270",
                            "left",
                            5253,
                            0,
                            "linear",
                            "${waste}",
                            '339px',
                            '339px'
                        ],
                        [
                            "eid275",
                            "left",
                            18668,
                            1071,
                            "linear",
                            "${waste}",
                            '339px',
                            '391px'
                        ],
                        [
                            "eid278",
                            "left",
                            20000,
                            256,
                            "linear",
                            "${waste}",
                            '391px',
                            '339px'
                        ],
                        [
                            "eid284",
                            "left",
                            20920,
                            1071,
                            "linear",
                            "${waste}",
                            '339px',
                            '391px'
                        ],
                        [
                            "eid285",
                            "left",
                            22252,
                            256,
                            "linear",
                            "${waste}",
                            '391px',
                            '339px'
                        ],
                        [
                            "eid290",
                            "left",
                            23172,
                            1071,
                            "linear",
                            "${waste}",
                            '339px',
                            '391px'
                        ],
                        [
                            "eid291",
                            "left",
                            24504,
                            256,
                            "linear",
                            "${waste}",
                            '391px',
                            '339px'
                        ],
                        [
                            "eid167",
                            "width",
                            0,
                            0,
                            "linear",
                            "${red}",
                            '35px',
                            '35px'
                        ],
                        [
                            "eid174",
                            "left",
                            0,
                            0,
                            "linear",
                            "${purple}",
                            '470px',
                            '470px'
                        ],
                        [
                            "eid5",
                            "display",
                            0,
                            0,
                            "linear",
                            "${yello}",
                            'none',
                            'block'
                        ],
                        [
                            "eid109",
                            "opacity",
                            6785,
                            180,
                            "linear",
                            "${red}",
                            '0',
                            '1'
                        ],
                        [
                            "eid155",
                            "width",
                            0,
                            0,
                            "linear",
                            "${cyan}",
                            '35px',
                            '35px'
                        ],
                        [
                            "eid153",
                            "height",
                            0,
                            0,
                            "linear",
                            "${cyan}",
                            '138px',
                            '138px'
                        ],
                        [
                            "eid115",
                            "display",
                            0,
                            0,
                            "linear",
                            "${heal}",
                            'block',
                            'block'
                        ],
                        [
                            "eid147",
                            "height",
                            0,
                            0,
                            "linear",
                            "${yello}",
                            '138px',
                            '138px'
                        ],
                            [ "eid422", "trigger", 0, function executeMediaFunction(e, data) { this._executeMediaAction(e, data); }, ['play', '${cell2}', [] ] ],
                            [ "eid423", "trigger", 0, function executeMediaFunction(e, data) { this._executeMediaAction(e, data); }, ['play', '${cell22}', [] ] ]
                    ]
                }
            }
        };

    AdobeEdge.registerCompositionDefn(compId, symbols, fonts, scripts, resources, opts);

    if (!window.edge_authoring_mode) AdobeEdge.getComposition(compId).load("cell_edgeActions.js");
})("EDGE-40303185");
