/*jslint */
/*global AdobeEdge: false, window: false, document: false, console:false, alert: false */
(function (compId) {

    "use strict";
    var im='images/',
        aud='media/',
        vid='media/',
        js='js/',
        fonts = {
        },
        opts = {
            'gAudioPreloadPreference': 'auto',
            'gVideoPreloadPreference': 'auto'
        },
        resources = [
        ],
        scripts = [
        ],
        symbols = {
            "stage": {
                version: "6.0.0",
                minimumCompatibleVersion: "5.0.0",
                build: "6.0.0.400",
                scaleToFit: "none",
                centerStage: "none",
                resizeInstances: true,
                content: {
                    dom: [
                        {
                            id: 'bodyveins',
                            display: 'block',
                            type: 'image',
                            rect: ['192px', '-468px', '572px', '1265px', 'auto', 'auto'],
                            opacity: '1',
                            fill: ["rgba(0,0,0,0)",im+"bodyveins.svg",'0px','0px']
                        },
                        {
                            id: 'heart',
                            display: 'block',
                            type: 'image',
                            rect: ['30px', '-214px', '88px', '117px', 'auto', 'auto'],
                            opacity: '1',
                            fill: ["rgba(0,0,0,0)",im+"heart.svg",'0px','0px']
                        },
                        {
                            id: 'blankbody',
                            display: 'block',
                            type: 'image',
                            rect: ['193px', '18px', '164px', '363px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"blankbody.svg",'0px','0px']
                        },
                        {
                            id: 'sweat1',
                            display: 'block',
                            type: 'image',
                            rect: ['317px', '93px', '6px', '15px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"sweat1.svg",'0px','0px']
                        },
                        {
                            id: 'sweat2',
                            display: 'block',
                            type: 'image',
                            rect: ['300px', '192px', '3px', '8px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"sweat2.svg",'0px','0px']
                        },
                        {
                            id: 'sweat3',
                            display: 'block',
                            type: 'image',
                            rect: ['251px', '126px', '6px', '15px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"sweat3.svg",'0px','0px']
                        },
                        {
                            id: 'sweat4',
                            display: 'block',
                            type: 'image',
                            rect: ['224px', '104px', '3px', '8px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"sweat4.svg",'0px','0px']
                        },
                        {
                            id: 'machine',
                            display: 'none',
                            type: 'image',
                            rect: ['409px', '8px', '128px', '214px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"machine.svg",'0px','0px']
                        },
                        {
                            id: 'brick',
                            display: 'block',
                            type: 'image',
                            rect: ['358px', '39px', '27px', '108px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"brick.svg",'0px','0px']
                        },
                        {
                            id: 'red',
                            display: 'block',
                            type: 'image',
                            rect: ['358px', '39px', '27px', '108px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"red.svg",'0px','0px']
                        },
                        {
                            id: 'bloodorange',
                            display: 'block',
                            type: 'image',
                            rect: ['358px', '39px', '27px', '108px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"bloodorange.svg",'0px','0px']
                        },
                        {
                            id: 'orange',
                            display: 'block',
                            type: 'image',
                            rect: ['358px', '39px', '27px', '108px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"orange.svg",'0px','0px']
                        },
                        {
                            id: 'yello',
                            display: 'block',
                            type: 'image',
                            rect: ['358px', '39px', '27px', '108px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"yello.svg",'0px','0px']
                        },
                        {
                            id: 'lime',
                            display: 'block',
                            type: 'image',
                            rect: ['358px', '39px', '27px', '108px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"lime.svg",'0px','0px']
                        },
                        {
                            id: 'olive',
                            display: 'block',
                            type: 'image',
                            rect: ['358px', '39px', '27px', '108px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"olive.svg",'0px','0px']
                        },
                        {
                            id: 'cyan',
                            display: 'block',
                            type: 'image',
                            rect: ['358px', '39px', '27px', '108px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"cyan.svg",'0px','0px']
                        },
                        {
                            id: 'blue',
                            display: 'block',
                            type: 'image',
                            rect: ['358px', '39px', '27px', '108px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"blue.svg",'0px','0px']
                        },
                        {
                            id: 'purple',
                            display: 'block',
                            type: 'image',
                            rect: ['358px', '39px', '27px', '108px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"purple.svg",'0px','0px']
                        },
                        {
                            id: 'veinbottom2',
                            display: 'none',
                            type: 'image',
                            rect: ['387px', '-35px', '139px', '164px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"veinbottom2.svg",'0px','0px']
                        },
                        {
                            id: 'monocyte',
                            display: 'none',
                            type: 'image',
                            rect: ['502px', '38px', '28px', '26px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"monocyte.svg",'0px','0px']
                        },
                        {
                            id: 'blood',
                            display: 'none',
                            type: 'image',
                            rect: ['463px', '37px', '20px', '14px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"blood.svg",'0px','0px']
                        },
                        {
                            id: 'blood2',
                            display: 'none',
                            type: 'image',
                            rect: ['482px', '29px', '20px', '14px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"blood2.svg",'0px','0px']
                        },
                        {
                            id: 'veintop2',
                            display: 'none',
                            type: 'image',
                            rect: ['387px', '-35px', '122px', '164px', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"veintop2.svg",'0px','0px']
                        },
                        {
                            id: 'boy3',
                            display: 'none',
                            type: 'audio',
                            tag: 'audio',
                            rect: ['0', '0', '320px', '45px', 'auto', 'auto'],
                            source: [aud+"boy3.wav"],
                            preload: 'auto'
                        }
                    ],
                    style: {
                        '${Stage}': {
                            isStage: true,
                            rect: ['null', 'null', '550px', '400px', 'auto', 'auto'],
                            overflow: 'hidden',
                            fill: ["rgba(255,255,255,1)"]
                        }
                    }
                },
                timeline: {
                    duration: 59329.478,
                    autoPlay: true,
                    data: [
                        [
                            "eid144",
                            "top",
                            4000,
                            2000,
                            "linear",
                            "${heart}",
                            '90px',
                            '-214px'
                        ],
                        [
                            "eid150",
                            "top",
                            7431,
                            30020,
                            "linear",
                            "${heart}",
                            '-214px',
                            '126px'
                        ],
                        [
                            "eid263",
                            "top",
                            40354,
                            354,
                            "linear",
                            "${heart}",
                            '126px',
                            '116px'
                        ],
                        [
                            "eid266",
                            "top",
                            40708,
                            646,
                            "linear",
                            "${heart}",
                            '116px',
                            '126px'
                        ],
                        [
                            "eid459",
                            "top",
                            41354,
                            354,
                            "linear",
                            "${heart}",
                            '126px',
                            '116px'
                        ],
                        [
                            "eid460",
                            "top",
                            41708,
                            646,
                            "linear",
                            "${heart}",
                            '116px',
                            '126px'
                        ],
                        [
                            "eid467",
                            "top",
                            42354,
                            354,
                            "linear",
                            "${heart}",
                            '126px',
                            '116px'
                        ],
                        [
                            "eid468",
                            "top",
                            42708,
                            646,
                            "linear",
                            "${heart}",
                            '116px',
                            '126px'
                        ],
                        [
                            "eid475",
                            "top",
                            43354,
                            354,
                            "linear",
                            "${heart}",
                            '126px',
                            '116px'
                        ],
                        [
                            "eid476",
                            "top",
                            43708,
                            646,
                            "linear",
                            "${heart}",
                            '116px',
                            '126px'
                        ],
                        [
                            "eid483",
                            "top",
                            44354,
                            354,
                            "linear",
                            "${heart}",
                            '126px',
                            '116px'
                        ],
                        [
                            "eid484",
                            "top",
                            44708,
                            646,
                            "linear",
                            "${heart}",
                            '116px',
                            '126px'
                        ],
                        [
                            "eid491",
                            "top",
                            45354,
                            354,
                            "linear",
                            "${heart}",
                            '126px',
                            '116px'
                        ],
                        [
                            "eid492",
                            "top",
                            45708,
                            646,
                            "linear",
                            "${heart}",
                            '116px',
                            '126px'
                        ],
                        [
                            "eid411",
                            "top",
                            52000,
                            1047,
                            "linear",
                            "${heart}",
                            '116px',
                            '90px'
                        ],
                        [
                            "eid381",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${sweat2}",
                            '0',
                            '0'
                        ],
                        [
                            "eid385",
                            "opacity",
                            46354,
                            925,
                            "linear",
                            "${sweat2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid405",
                            "opacity",
                            53047,
                            2139,
                            "linear",
                            "${sweat2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid425",
                            "display",
                            0,
                            0,
                            "linear",
                            "${cyan}",
                            'block',
                            'block'
                        ],
                        [
                            "eid369",
                            "display",
                            0,
                            0,
                            "linear",
                            "${heart}",
                            'block',
                            'block'
                        ],
                        [
                            "eid201",
                            "top",
                            34774,
                            724,
                            "linear",
                            "${veintop2}",
                            '18px',
                            '8px'
                        ],
                        [
                            "eid214",
                            "top",
                            35498,
                            976,
                            "linear",
                            "${veintop2}",
                            '8px',
                            '-24px'
                        ],
                        [
                            "eid231",
                            "top",
                            36474,
                            437,
                            "linear",
                            "${veintop2}",
                            '-24px',
                            '-35px'
                        ],
                        [
                            "eid226",
                            "top",
                            36911,
                            850,
                            "linear",
                            "${veintop2}",
                            '-35px',
                            '-18px'
                        ],
                        [
                            "eid372",
                            "display",
                            0,
                            0,
                            "linear",
                            "${blankbody}",
                            'block',
                            'block'
                        ],
                        [
                            "eid181",
                            "left",
                            34774,
                            3658,
                            "linear",
                            "${blood2}",
                            '432px',
                            '482px'
                        ],
                        [
                            "eid185",
                            "top",
                            34774,
                            3658,
                            "linear",
                            "${monocyte}",
                            '30px',
                            '38px'
                        ],
                        [
                            "eid172",
                            "opacity",
                            34774,
                            724,
                            "linear",
                            "${monocyte}",
                            '0',
                            '1'
                        ],
                        [
                            "eid248",
                            "opacity",
                            37451,
                            462,
                            "linear",
                            "${monocyte}",
                            '1',
                            '0'
                        ],
                        [
                            "eid370",
                            "opacity",
                            46354,
                            925,
                            "linear",
                            "${bodyveins}",
                            '1',
                            '0'
                        ],
                        [
                            "eid409",
                            "opacity",
                            53047,
                            2108,
                            "linear",
                            "${bodyveins}",
                            '0',
                            '1'
                        ],
                        [
                            "eid393",
                            "left",
                            46354,
                            4295,
                            "linear",
                            "${sweat4}",
                            '224px',
                            '226px'
                        ],
                        [
                            "eid395",
                            "left",
                            50649,
                            2398,
                            "linear",
                            "${sweat4}",
                            '226px',
                            '216px'
                        ],
                        [
                            "eid151",
                            "display",
                            25000,
                            0,
                            "linear",
                            "${machine}",
                            'none',
                            'block'
                        ],
                        [
                            "eid423",
                            "display",
                            0,
                            0,
                            "linear",
                            "${lime}",
                            'block',
                            'block'
                        ],
                        [
                            "eid200",
                            "top",
                            34774,
                            724,
                            "linear",
                            "${veinbottom2}",
                            '18px',
                            '8px'
                        ],
                        [
                            "eid216",
                            "top",
                            35498,
                            976,
                            "linear",
                            "${veinbottom2}",
                            '8px',
                            '-24px'
                        ],
                        [
                            "eid233",
                            "top",
                            36474,
                            437,
                            "linear",
                            "${veinbottom2}",
                            '-24px',
                            '-35px'
                        ],
                        [
                            "eid228",
                            "top",
                            36911,
                            850,
                            "linear",
                            "${veinbottom2}",
                            '-35px',
                            '-18px'
                        ],
                        [
                            "eid390",
                            "top",
                            46354,
                            4295,
                            "linear",
                            "${sweat3}",
                            '126px',
                            '162px'
                        ],
                        [
                            "eid398",
                            "top",
                            50649,
                            2398,
                            "linear",
                            "${sweat3}",
                            '162px',
                            '206px'
                        ],
                        [
                            "eid389",
                            "left",
                            46354,
                            4295,
                            "linear",
                            "${sweat3}",
                            '251px',
                            '253px'
                        ],
                        [
                            "eid397",
                            "left",
                            50649,
                            2398,
                            "linear",
                            "${sweat3}",
                            '253px',
                            '244px'
                        ],
                        [
                            "eid424",
                            "display",
                            0,
                            0,
                            "linear",
                            "${olive}",
                            'block',
                            'block'
                        ],
                        [
                            "eid295",
                            "top",
                            34774,
                            6226,
                            "linear",
                            "${blood}",
                            '37px',
                            '119px'
                        ],
                        [
                            "eid297",
                            "top",
                            41000,
                            1000,
                            "linear",
                            "${blood}",
                            '119px',
                            '105px'
                        ],
                        [
                            "eid301",
                            "top",
                            42000,
                            1000,
                            "linear",
                            "${blood}",
                            '105px',
                            '133px'
                        ],
                        [
                            "eid304",
                            "top",
                            43000,
                            1000,
                            "linear",
                            "${blood}",
                            '133px',
                            '200px'
                        ],
                        [
                            "eid212",
                            "width",
                            34774,
                            1974,
                            "linear",
                            "${veintop2}",
                            '122px',
                            '156px'
                        ],
                        [
                            "eid220",
                            "width",
                            36748,
                            1013,
                            "linear",
                            "${veintop2}",
                            '156px',
                            '117px'
                        ],
                        [
                            "eid184",
                            "left",
                            34774,
                            3658,
                            "linear",
                            "${monocyte}",
                            '459px',
                            '502px'
                        ],
                        [
                            "eid392",
                            "top",
                            46354,
                            4295,
                            "linear",
                            "${sweat2}",
                            '192px',
                            '228px'
                        ],
                        [
                            "eid400",
                            "top",
                            50649,
                            2398,
                            "linear",
                            "${sweat2}",
                            '228px',
                            '272px'
                        ],
                        [
                            "eid380",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${sweat3}",
                            '0',
                            '0'
                        ],
                        [
                            "eid384",
                            "opacity",
                            46354,
                            925,
                            "linear",
                            "${sweat3}",
                            '0',
                            '1'
                        ],
                        [
                            "eid406",
                            "opacity",
                            53047,
                            2139,
                            "linear",
                            "${sweat3}",
                            '1',
                            '0'
                        ],
                        [
                            "eid145",
                            "left",
                            4000,
                            2000,
                            "linear",
                            "${heart}",
                            '262px',
                            '30px'
                        ],
                        [
                            "eid149",
                            "left",
                            7431,
                            30020,
                            "linear",
                            "${heart}",
                            '30px',
                            '233px'
                        ],
                        [
                            "eid264",
                            "left",
                            40354,
                            354,
                            "linear",
                            "${heart}",
                            '233px',
                            '223px'
                        ],
                        [
                            "eid265",
                            "left",
                            40708,
                            646,
                            "linear",
                            "${heart}",
                            '223px',
                            '233px'
                        ],
                        [
                            "eid463",
                            "left",
                            41354,
                            354,
                            "linear",
                            "${heart}",
                            '233px',
                            '223px'
                        ],
                        [
                            "eid464",
                            "left",
                            41708,
                            646,
                            "linear",
                            "${heart}",
                            '223px',
                            '233px'
                        ],
                        [
                            "eid471",
                            "left",
                            42354,
                            354,
                            "linear",
                            "${heart}",
                            '233px',
                            '223px'
                        ],
                        [
                            "eid472",
                            "left",
                            42708,
                            646,
                            "linear",
                            "${heart}",
                            '223px',
                            '233px'
                        ],
                        [
                            "eid479",
                            "left",
                            43354,
                            354,
                            "linear",
                            "${heart}",
                            '233px',
                            '223px'
                        ],
                        [
                            "eid480",
                            "left",
                            43708,
                            646,
                            "linear",
                            "${heart}",
                            '223px',
                            '233px'
                        ],
                        [
                            "eid487",
                            "left",
                            44354,
                            354,
                            "linear",
                            "${heart}",
                            '233px',
                            '223px'
                        ],
                        [
                            "eid488",
                            "left",
                            44708,
                            646,
                            "linear",
                            "${heart}",
                            '223px',
                            '233px'
                        ],
                        [
                            "eid495",
                            "left",
                            45354,
                            354,
                            "linear",
                            "${heart}",
                            '233px',
                            '223px'
                        ],
                        [
                            "eid496",
                            "left",
                            45708,
                            646,
                            "linear",
                            "${heart}",
                            '223px',
                            '233px'
                        ],
                        [
                            "eid410",
                            "left",
                            52000,
                            1047,
                            "linear",
                            "${heart}",
                            '233px',
                            '262px'
                        ],
                        [
                            "eid376",
                            "display",
                            0,
                            0,
                            "linear",
                            "${sweat3}",
                            'block',
                            'block'
                        ],
                        [
                            "eid368",
                            "display",
                            0,
                            0,
                            "linear",
                            "${bodyveins}",
                            'block',
                            'block'
                        ],
                        [
                            "eid371",
                            "opacity",
                            46354,
                            925,
                            "linear",
                            "${heart}",
                            '1',
                            '0'
                        ],
                        [
                            "eid408",
                            "opacity",
                            53047,
                            2108,
                            "linear",
                            "${heart}",
                            '0',
                            '1'
                        ],
                        [
                            "eid420",
                            "display",
                            0,
                            0,
                            "linear",
                            "${bloodorange}",
                            'block',
                            'block'
                        ],
                        [
                            "eid426",
                            "display",
                            0,
                            0,
                            "linear",
                            "${blue}",
                            'block',
                            'block'
                        ],
                        [
                            "eid378",
                            "display",
                            0,
                            0,
                            "linear",
                            "${sweat1}",
                            'block',
                            'block'
                        ],
                        [
                            "eid142",
                            "width",
                            4000,
                            2000,
                            "linear",
                            "${bodyveins}",
                            '166px',
                            '572px'
                        ],
                        [
                            "eid416",
                            "width",
                            52000,
                            1047,
                            "linear",
                            "${bodyveins}",
                            '572px',
                            '166px'
                        ],
                        [
                            "eid437",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${brick}",
                            '0',
                            '0'
                        ],
                        [
                            "eid447",
                            "opacity",
                            52344,
                            421,
                            "linear",
                            "${brick}",
                            '0',
                            '1'
                        ],
                        [
                            "eid457",
                            "opacity",
                            53482,
                            1542,
                            "linear",
                            "${brick}",
                            '1',
                            '0'
                        ],
                        [
                            "eid141",
                            "left",
                            4000,
                            2000,
                            "linear",
                            "${bodyveins}",
                            '192px',
                            '-209px'
                        ],
                        [
                            "eid147",
                            "left",
                            7431,
                            30020,
                            "linear",
                            "${bodyveins}",
                            '-209px',
                            '-6px'
                        ],
                        [
                            "eid414",
                            "left",
                            52000,
                            1047,
                            "linear",
                            "${bodyveins}",
                            '-6px',
                            '192px'
                        ],
                        [
                            "eid199",
                            "height",
                            34774,
                            724,
                            "linear",
                            "${veintop2}",
                            '47px',
                            '68px'
                        ],
                        [
                            "eid211",
                            "height",
                            35498,
                            1413,
                            "linear",
                            "${veintop2}",
                            '68px',
                            '164px'
                        ],
                        [
                            "eid219",
                            "height",
                            36911,
                            850,
                            "linear",
                            "${veintop2}",
                            '164px',
                            '123px'
                        ],
                        [
                            "eid182",
                            "top",
                            34774,
                            3658,
                            "linear",
                            "${blood2}",
                            '44px',
                            '29px'
                        ],
                        [
                            "eid163",
                            "display",
                            34774,
                            0,
                            "linear",
                            "${monocyte}",
                            'none',
                            'block'
                        ],
                        [
                            "eid213",
                            "left",
                            34774,
                            1700,
                            "linear",
                            "${veintop2}",
                            '387px',
                            '379px'
                        ],
                        [
                            "eid230",
                            "left",
                            36474,
                            274,
                            "linear",
                            "${veintop2}",
                            '379px',
                            '373px'
                        ],
                        [
                            "eid225",
                            "left",
                            36748,
                            1013,
                            "linear",
                            "${veintop2}",
                            '373px',
                            '409px'
                        ],
                        [
                            "eid168",
                            "opacity",
                            34774,
                            724,
                            "linear",
                            "${blood}",
                            '0',
                            '1'
                        ],
                        [
                            "eid306",
                            "opacity",
                            35498,
                            266,
                            "linear",
                            "${blood}",
                            '1',
                            '0'
                        ],
                        [
                            "eid293",
                            "opacity",
                            41000,
                            617,
                            "linear",
                            "${blood}",
                            '0',
                            '1'
                        ],
                        [
                            "eid305",
                            "opacity",
                            43000,
                            1000,
                            "linear",
                            "${blood}",
                            '1',
                            '0'
                        ],
                        [
                            "eid419",
                            "display",
                            0,
                            0,
                            "linear",
                            "${red}",
                            'block',
                            'block'
                        ],
                        [
                            "eid170",
                            "opacity",
                            34774,
                            724,
                            "linear",
                            "${veinbottom2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid249",
                            "opacity",
                            37451,
                            462,
                            "linear",
                            "${veinbottom2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid180",
                            "left",
                            34774,
                            3658,
                            "linear",
                            "${blood}",
                            '399px',
                            '463px'
                        ],
                        [
                            "eid294",
                            "left",
                            38432,
                            2568,
                            "linear",
                            "${blood}",
                            '463px',
                            '280px'
                        ],
                        [
                            "eid296",
                            "left",
                            41000,
                            1000,
                            "linear",
                            "${blood}",
                            '280px',
                            '326px'
                        ],
                        [
                            "eid300",
                            "left",
                            42000,
                            1000,
                            "linear",
                            "${blood}",
                            '326px',
                            '366px'
                        ],
                        [
                            "eid303",
                            "left",
                            43000,
                            1000,
                            "linear",
                            "${blood}",
                            '366px',
                            '389px'
                        ],
                        [
                            "eid166",
                            "opacity",
                            34774,
                            724,
                            "linear",
                            "${blood2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid245",
                            "opacity",
                            37451,
                            462,
                            "linear",
                            "${blood2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid427",
                            "display",
                            0,
                            0,
                            "linear",
                            "${purple}",
                            'block',
                            'block'
                        ],
                        [
                            "eid379",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${sweat1}",
                            '0',
                            '0'
                        ],
                        [
                            "eid383",
                            "opacity",
                            46354,
                            925,
                            "linear",
                            "${sweat1}",
                            '0',
                            '1'
                        ],
                        [
                            "eid404",
                            "opacity",
                            53047,
                            2139,
                            "linear",
                            "${sweat1}",
                            '1',
                            '0'
                        ],
                        [
                            "eid433",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${blue}",
                            '0',
                            '0'
                        ],
                        [
                            "eid439",
                            "opacity",
                            48747,
                            592,
                            "linear",
                            "${blue}",
                            '0',
                            '1'
                        ],
                        [
                            "eid453",
                            "opacity",
                            53482,
                            1542,
                            "linear",
                            "${blue}",
                            '1',
                            '0'
                        ],
                        [
                            "eid429",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${lime}",
                            '0',
                            '0'
                        ],
                        [
                            "eid442",
                            "opacity",
                            50366,
                            465,
                            "linear",
                            "${lime}",
                            '0',
                            '1'
                        ],
                        [
                            "eid449",
                            "opacity",
                            53482,
                            1542,
                            "linear",
                            "${lime}",
                            '1',
                            '0'
                        ],
                        [
                            "eid436",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${orange}",
                            '0',
                            '0'
                        ],
                        [
                            "eid444",
                            "opacity",
                            51250,
                            500,
                            "linear",
                            "${orange}",
                            '0',
                            '1'
                        ],
                        [
                            "eid456",
                            "opacity",
                            53482,
                            1542,
                            "linear",
                            "${orange}",
                            '1',
                            '0'
                        ],
                        [
                            "eid375",
                            "display",
                            0,
                            0,
                            "linear",
                            "${sweat4}",
                            'block',
                            'block'
                        ],
                        [
                            "eid146",
                            "width",
                            4000,
                            2000,
                            "linear",
                            "${heart}",
                            '27px',
                            '93px'
                        ],
                        [
                            "eid261",
                            "width",
                            40354,
                            354,
                            "linear",
                            "${heart}",
                            '93px',
                            '103px'
                        ],
                        [
                            "eid267",
                            "width",
                            40708,
                            646,
                            "linear",
                            "${heart}",
                            '103px',
                            '93px'
                        ],
                        [
                            "eid465",
                            "width",
                            41354,
                            354,
                            "linear",
                            "${heart}",
                            '93px',
                            '103px'
                        ],
                        [
                            "eid466",
                            "width",
                            41708,
                            646,
                            "linear",
                            "${heart}",
                            '103px',
                            '93px'
                        ],
                        [
                            "eid473",
                            "width",
                            42354,
                            354,
                            "linear",
                            "${heart}",
                            '93px',
                            '103px'
                        ],
                        [
                            "eid474",
                            "width",
                            42708,
                            646,
                            "linear",
                            "${heart}",
                            '103px',
                            '93px'
                        ],
                        [
                            "eid481",
                            "width",
                            43354,
                            354,
                            "linear",
                            "${heart}",
                            '93px',
                            '103px'
                        ],
                        [
                            "eid482",
                            "width",
                            43708,
                            646,
                            "linear",
                            "${heart}",
                            '103px',
                            '93px'
                        ],
                        [
                            "eid489",
                            "width",
                            44354,
                            354,
                            "linear",
                            "${heart}",
                            '93px',
                            '103px'
                        ],
                        [
                            "eid490",
                            "width",
                            44708,
                            646,
                            "linear",
                            "${heart}",
                            '103px',
                            '93px'
                        ],
                        [
                            "eid497",
                            "width",
                            45354,
                            354,
                            "linear",
                            "${heart}",
                            '93px',
                            '103px'
                        ],
                        [
                            "eid498",
                            "width",
                            45708,
                            646,
                            "linear",
                            "${heart}",
                            '103px',
                            '93px'
                        ],
                        [
                            "eid412",
                            "width",
                            52000,
                            1047,
                            "linear",
                            "${heart}",
                            '103px',
                            '27px'
                        ],
                        [
                            "eid382",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${sweat4}",
                            '0',
                            '0'
                        ],
                        [
                            "eid386",
                            "opacity",
                            46354,
                            925,
                            "linear",
                            "${sweat4}",
                            '0',
                            '1'
                        ],
                        [
                            "eid407",
                            "opacity",
                            53047,
                            2139,
                            "linear",
                            "${sweat4}",
                            '1',
                            '0'
                        ],
                        [
                            "eid434",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${purple}",
                            '0',
                            '0'
                        ],
                        [
                            "eid438",
                            "opacity",
                            48000,
                            747,
                            "linear",
                            "${purple}",
                            '0',
                            '1'
                        ],
                        [
                            "eid454",
                            "opacity",
                            53482,
                            1542,
                            "linear",
                            "${purple}",
                            '1',
                            '0'
                        ],
                        [
                            "eid432",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${red}",
                            '0',
                            '0'
                        ],
                        [
                            "eid446",
                            "opacity",
                            52024,
                            320,
                            "linear",
                            "${red}",
                            '0',
                            '1'
                        ],
                        [
                            "eid452",
                            "opacity",
                            53482,
                            1542,
                            "linear",
                            "${red}",
                            '1',
                            '0'
                        ],
                        [
                            "eid431",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${cyan}",
                            '0',
                            '0'
                        ],
                        [
                            "eid440",
                            "opacity",
                            49339,
                            556,
                            "linear",
                            "${cyan}",
                            '0',
                            '1'
                        ],
                        [
                            "eid451",
                            "opacity",
                            53482,
                            1542,
                            "linear",
                            "${cyan}",
                            '1',
                            '0'
                        ],
                        [
                            "eid430",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${yello}",
                            '0',
                            '0'
                        ],
                        [
                            "eid443",
                            "opacity",
                            50831,
                            419,
                            "linear",
                            "${yello}",
                            '0',
                            '1'
                        ],
                        [
                            "eid450",
                            "opacity",
                            53482,
                            1542,
                            "linear",
                            "${yello}",
                            '1',
                            '0'
                        ],
                        [
                            "eid428",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${olive}",
                            '0',
                            '0'
                        ],
                        [
                            "eid441",
                            "opacity",
                            49895,
                            471,
                            "linear",
                            "${olive}",
                            '0',
                            '1'
                        ],
                        [
                            "eid448",
                            "opacity",
                            53482,
                            1542,
                            "linear",
                            "${olive}",
                            '1',
                            '0'
                        ],
                        [
                            "eid160",
                            "display",
                            34774,
                            0,
                            "linear",
                            "${veintop2}",
                            'none',
                            'block'
                        ],
                        [
                            "eid391",
                            "left",
                            46354,
                            4295,
                            "linear",
                            "${sweat2}",
                            '300px',
                            '302px'
                        ],
                        [
                            "eid399",
                            "left",
                            50649,
                            2398,
                            "linear",
                            "${sweat2}",
                            '302px',
                            '305px'
                        ],
                        [
                            "eid139",
                            "height",
                            4000,
                            2000,
                            "linear",
                            "${bodyveins}",
                            '367px',
                            '1265px'
                        ],
                        [
                            "eid417",
                            "height",
                            52000,
                            1047,
                            "linear",
                            "${bodyveins}",
                            '1265px',
                            '367px'
                        ],
                        [
                            "eid153",
                            "opacity",
                            25000,
                            2430,
                            "linear",
                            "${machine}",
                            '0',
                            '1'
                        ],
                        [
                            "eid154",
                            "opacity",
                            28000,
                            1700,
                            "linear",
                            "${machine}",
                            '1',
                            '0'
                        ],
                        [
                            "eid418",
                            "display",
                            0,
                            0,
                            "linear",
                            "${brick}",
                            'block',
                            'block'
                        ],
                        [
                            "eid421",
                            "display",
                            0,
                            0,
                            "linear",
                            "${orange}",
                            'block',
                            'block'
                        ],
                        [
                            "eid210",
                            "width",
                            34774,
                            1974,
                            "linear",
                            "${veinbottom2}",
                            '139px',
                            '177px'
                        ],
                        [
                            "eid218",
                            "width",
                            36748,
                            1013,
                            "linear",
                            "${veinbottom2}",
                            '177px',
                            '133px'
                        ],
                        [
                            "eid435",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${bloodorange}",
                            '0',
                            '0'
                        ],
                        [
                            "eid445",
                            "opacity",
                            51750,
                            274,
                            "linear",
                            "${bloodorange}",
                            '0',
                            '1'
                        ],
                        [
                            "eid455",
                            "opacity",
                            53482,
                            1542,
                            "linear",
                            "${bloodorange}",
                            '1',
                            '0'
                        ],
                        [
                            "eid377",
                            "display",
                            0,
                            0,
                            "linear",
                            "${sweat2}",
                            'block',
                            'block'
                        ],
                        [
                            "eid215",
                            "left",
                            34774,
                            1700,
                            "linear",
                            "${veinbottom2}",
                            '387px',
                            '379px'
                        ],
                        [
                            "eid232",
                            "left",
                            36474,
                            274,
                            "linear",
                            "${veinbottom2}",
                            '379px',
                            '373px'
                        ],
                        [
                            "eid227",
                            "left",
                            36748,
                            1013,
                            "linear",
                            "${veinbottom2}",
                            '373px',
                            '409px'
                        ],
                        [
                            "eid394",
                            "top",
                            46354,
                            4295,
                            "linear",
                            "${sweat4}",
                            '104px',
                            '140px'
                        ],
                        [
                            "eid396",
                            "top",
                            50649,
                            2398,
                            "linear",
                            "${sweat4}",
                            '140px',
                            '162px'
                        ],
                        [
                            "eid161",
                            "display",
                            34774,
                            0,
                            "linear",
                            "${blood2}",
                            'none',
                            'block'
                        ],
                        [
                            "eid373",
                            "opacity",
                            0,
                            0,
                            "linear",
                            "${blankbody}",
                            '0',
                            '0'
                        ],
                        [
                            "eid374",
                            "opacity",
                            46354,
                            925,
                            "linear",
                            "${blankbody}",
                            '0',
                            '1'
                        ],
                        [
                            "eid403",
                            "opacity",
                            53047,
                            2139,
                            "linear",
                            "${blankbody}",
                            '1',
                            '0'
                        ],
                        [
                            "eid140",
                            "top",
                            4000,
                            2000,
                            "linear",
                            "${bodyveins}",
                            '16px',
                            '-468px'
                        ],
                        [
                            "eid148",
                            "top",
                            7431,
                            30020,
                            "linear",
                            "${bodyveins}",
                            '-468px',
                            '-128px'
                        ],
                        [
                            "eid415",
                            "top",
                            52000,
                            1047,
                            "linear",
                            "${bodyveins}",
                            '-128px',
                            '16px'
                        ],
                        [
                            "eid388",
                            "top",
                            46354,
                            4295,
                            "linear",
                            "${sweat1}",
                            '93px',
                            '129px'
                        ],
                        [
                            "eid401",
                            "top",
                            50649,
                            2398,
                            "linear",
                            "${sweat1}",
                            '129px',
                            '158px'
                        ],
                        [
                            "eid198",
                            "height",
                            34774,
                            724,
                            "linear",
                            "${veinbottom2}",
                            '47px',
                            '68px'
                        ],
                        [
                            "eid209",
                            "height",
                            35498,
                            1413,
                            "linear",
                            "${veinbottom2}",
                            '68px',
                            '164px'
                        ],
                        [
                            "eid217",
                            "height",
                            36911,
                            850,
                            "linear",
                            "${veinbottom2}",
                            '164px',
                            '123px'
                        ],
                        [
                            "eid422",
                            "display",
                            0,
                            0,
                            "linear",
                            "${yello}",
                            'block',
                            'block'
                        ],
                        [
                            "eid174",
                            "opacity",
                            34774,
                            724,
                            "linear",
                            "${veintop2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid247",
                            "opacity",
                            37451,
                            462,
                            "linear",
                            "${veintop2}",
                            '1',
                            '0'
                        ],
                        [
                            "eid162",
                            "display",
                            34774,
                            0,
                            "linear",
                            "${blood}",
                            'none',
                            'block'
                        ],
                        [
                            "eid387",
                            "left",
                            46354,
                            4295,
                            "linear",
                            "${sweat1}",
                            '317px',
                            '319px'
                        ],
                        [
                            "eid402",
                            "left",
                            50649,
                            2398,
                            "linear",
                            "${sweat1}",
                            '319px',
                            '325px'
                        ],
                        [
                            "eid143",
                            "height",
                            4000,
                            2000,
                            "linear",
                            "${heart}",
                            '36px',
                            '123px'
                        ],
                        [
                            "eid262",
                            "height",
                            40354,
                            354,
                            "linear",
                            "${heart}",
                            '123px',
                            '130px'
                        ],
                        [
                            "eid268",
                            "height",
                            40708,
                            646,
                            "linear",
                            "${heart}",
                            '130px',
                            '123px'
                        ],
                        [
                            "eid461",
                            "height",
                            41354,
                            354,
                            "linear",
                            "${heart}",
                            '123px',
                            '130px'
                        ],
                        [
                            "eid462",
                            "height",
                            41708,
                            646,
                            "linear",
                            "${heart}",
                            '130px',
                            '123px'
                        ],
                        [
                            "eid469",
                            "height",
                            42354,
                            354,
                            "linear",
                            "${heart}",
                            '123px',
                            '130px'
                        ],
                        [
                            "eid470",
                            "height",
                            42708,
                            646,
                            "linear",
                            "${heart}",
                            '130px',
                            '123px'
                        ],
                        [
                            "eid477",
                            "height",
                            43354,
                            354,
                            "linear",
                            "${heart}",
                            '123px',
                            '130px'
                        ],
                        [
                            "eid478",
                            "height",
                            43708,
                            646,
                            "linear",
                            "${heart}",
                            '130px',
                            '123px'
                        ],
                        [
                            "eid485",
                            "height",
                            44354,
                            354,
                            "linear",
                            "${heart}",
                            '123px',
                            '130px'
                        ],
                        [
                            "eid486",
                            "height",
                            44708,
                            646,
                            "linear",
                            "${heart}",
                            '130px',
                            '123px'
                        ],
                        [
                            "eid493",
                            "height",
                            45354,
                            354,
                            "linear",
                            "${heart}",
                            '123px',
                            '130px'
                        ],
                        [
                            "eid494",
                            "height",
                            45708,
                            646,
                            "linear",
                            "${heart}",
                            '130px',
                            '123px'
                        ],
                        [
                            "eid413",
                            "height",
                            52000,
                            1047,
                            "linear",
                            "${heart}",
                            '133px',
                            '36px'
                        ],
                        [
                            "eid164",
                            "display",
                            34774,
                            0,
                            "linear",
                            "${veinbottom2}",
                            'none',
                            'block'
                        ],
                            [ "eid499", "trigger", 0, function executeMediaFunction(e, data) { this._executeMediaAction(e, data); }, ['play', '${boy3}', [] ] ]
                    ]
                }
            }
        };

    AdobeEdge.registerCompositionDefn(compId, symbols, fonts, scripts, resources, opts);

    if (!window.edge_authoring_mode) AdobeEdge.getComposition(compId).load("boy_edgeActions.js");
})("EDGE-39385733");
